{
  f()
  g()
  h()
  function f() { mstore(29400335157912315244266070412362164103369332044010299463143527189509193072640, mload(0x00)) }
  function g() { mstore(0x4100000000000000000000000000000000000000000000000000000000000000, mload(0x00)) }
  function h() { mstore("A", mload(0)) }
}
// ----
// step: equivalentFunctionCombiner
//
// {
//     f()
//     f()
//     f()
//     function f()
//     {
//         mstore(29400335157912315244266070412362164103369332044010299463143527189509193072640, mload(0x00))
//     }
//     function g()
//     {
//         mstore(0x4100000000000000000000000000000000000000000000000000000000000000, mload(0x00))
//     }
//     function h()
//     { mstore("A", mload(0)) }
// }
