(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

(* Contract *)
Module C.
  Definition f (α : list Value.t) : M :=
    match α with
    | [bytesAsCalldata] =>
      let _ :=
        (* Beginning of a node! *)
id: 6
src: 85:64:0
nodeType: InlineAssembly
AST: TODO YulJson
externalReferences: src: 117:22:0declaration: 3isSlot: sOffset: suffix: offsetalueSize: 
evmVersion: cancun
 in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End C.
