add_library(yul
	${GENERATED_POLYFILL_HEADERS}

	AsmAnalysis.cpp
	AsmAnalysis.h
	AsmAnalysisInfo.h
	AST.h
	AST.cpp
	ASTForward.h
	ASTLabelRegistry.cpp
	ASTLabelRegistry.h
	AsmJsonConverter.h
	AsmJsonConverter.cpp
	AsmJsonImporter.h
	AsmJsonImporter.cpp
	AsmParser.cpp
	AsmParser.h
	AsmPrinter.cpp
	AsmPrinter.h
	Builtins.h
	YulStack.h
	YulStack.cpp
	CompilabilityChecker.cpp
	CompilabilityChecker.h
	ControlFlowSideEffects.h
	ControlFlowSideEffectsCollector.cpp
	ControlFlowSideEffectsCollector.h
	Dialect.cpp
	Dialect.h
	Exceptions.h
	FunctionReferenceResolver.cpp
	FunctionReferenceResolver.h
	Object.cpp
	Object.h
	ObjectOptimizer.cpp
	ObjectOptimizer.h
	ObjectParser.cpp
	ObjectParser.h
	Scope.cpp
	Scope.h
	ScopeFiller.cpp
	ScopeFiller.h
	Utilities.cpp
	Utilities.h
	YulName.h
	YulString.h
	backends/evm/AbstractAssembly.h
	backends/evm/AsmCodeGen.cpp
	backends/evm/AsmCodeGen.h
	backends/evm/ConstantOptimiser.cpp
	backends/evm/ConstantOptimiser.h
	backends/evm/ControlFlowGraph.h
	backends/evm/ControlFlowGraphBuilder.cpp
	backends/evm/ControlFlowGraphBuilder.h
	backends/evm/EthAssemblyAdapter.cpp
	backends/evm/EthAssemblyAdapter.h
	backends/evm/EVMBuiltins.cpp
	backends/evm/EVMBuiltins.h
	backends/evm/EVMCodeTransform.cpp
	backends/evm/EVMCodeTransform.h
	backends/evm/EVMDialect.cpp
	backends/evm/EVMDialect.h
	backends/evm/EVMObjectCompiler.cpp
	backends/evm/EVMObjectCompiler.h
	backends/evm/EVMMetrics.cpp
	backends/evm/EVMMetrics.h
	backends/evm/NoOutputAssembly.h
	backends/evm/NoOutputAssembly.cpp
	backends/evm/OptimizedEVMCodeTransform.cpp
	backends/evm/OptimizedEVMCodeTransform.h
	backends/evm/StackHelpers.h
	backends/evm/StackLayoutGenerator.cpp
	backends/evm/StackLayoutGenerator.h
	backends/evm/VariableReferenceCounter.h
	backends/evm/VariableReferenceCounter.cpp
	backends/evm/ssa/BridgeFinder.h
	backends/evm/ssa/CallGraph.cpp
	backends/evm/ssa/CallGraph.h
	backends/evm/ssa/CodeTransform.cpp
	backends/evm/ssa/CodeTransform.h
	backends/evm/ssa/ControlFlowGraphs.cpp
	backends/evm/ssa/ControlFlowGraphs.h
	backends/evm/ssa/InstructionStore.h
	backends/evm/ssa/JunkAdmittingBlocksFinder.cpp
	backends/evm/ssa/JunkAdmittingBlocksFinder.h
	backends/evm/ssa/LivenessAnalysis.cpp
	backends/evm/ssa/LivenessAnalysis.h
	backends/evm/ssa/PhiInverse.cpp
	backends/evm/ssa/PhiInverse.h
	backends/evm/ssa/SSACFGLoopNestingForest.cpp
	backends/evm/ssa/SSACFGLoopNestingForest.h
	backends/evm/ssa/SSACFG.cpp
	backends/evm/ssa/SSACFG.h
	backends/evm/ssa/SSACFGBuilder.cpp
	backends/evm/ssa/SSACFGBuilder.h
	backends/evm/ssa/SSACFGDebugInfo.h
	backends/evm/ssa/SSACFGTypes.cpp
	backends/evm/ssa/SSACFGTypes.h
	backends/evm/ssa/ShuffleTrace.cpp
	backends/evm/ssa/ShuffleTrace.h
	backends/evm/ssa/Stack.h
	backends/evm/ssa/StackLayout.h
	backends/evm/ssa/StackLayoutGenerator.cpp
	backends/evm/ssa/StackLayoutGenerator.h
	backends/evm/ssa/StackShuffler.cpp
	backends/evm/ssa/StackShuffler.h
	backends/evm/ssa/StackSlot.cpp
	backends/evm/ssa/StackSlot.h
	backends/evm/ssa/StackSlotLiveness.h
	backends/evm/ssa/util/UseCountSet.h
	backends/evm/ssa/util/TLSFFreeList.h
	backends/evm/ssa/StackUtils.cpp
	backends/evm/ssa/StackUtils.h
	backends/evm/ssa/io/DotExporterBase.cpp
	backends/evm/ssa/io/DotExporterBase.h
	backends/evm/ssa/io/JSONExporter.cpp
	backends/evm/ssa/io/JSONExporter.h
	backends/evm/ssa/io/Printer.cpp
	backends/evm/ssa/io/Printer.h
	backends/evm/ssa/spill/Emitter.h
	backends/evm/ssa/spill/MemoryAddressing.cpp
	backends/evm/ssa/spill/MemoryAddressing.h
	backends/evm/ssa/spill/SpillSet.cpp
	backends/evm/ssa/spill/SpillSet.h
	backends/evm/ssa/stack/InstructionStackIn.cpp
	backends/evm/ssa/stack/InstructionStackIn.h
	backends/evm/ssa/stack/Shuffler.cpp
	backends/evm/ssa/stack/Shuffler.h
	backends/evm/ssa/transform/ConstantConditionFolder.cpp
	backends/evm/ssa/transform/ConstantConditionFolder.h
	backends/evm/ssa/transform/IdentityAndNopRemover.cpp
	backends/evm/ssa/transform/IdentityAndNopRemover.h
	backends/evm/ssa/transform/JumpThreader.cpp
	backends/evm/ssa/transform/JumpThreader.h
	backends/evm/ssa/transform/OptimizationPipeline.cpp
	backends/evm/ssa/transform/OptimizationPipeline.h
	backends/evm/ssa/transform/Outliner.cpp
	backends/evm/ssa/transform/Outliner.h
	backends/evm/ssa/transform/TrivialPhiEliminator.cpp
	backends/evm/ssa/transform/TrivialPhiEliminator.h
	backends/evm/ssa/transform/UnreachableBlockCleaner.cpp
	backends/evm/ssa/transform/UnreachableBlockCleaner.h
	backends/evm/ssa/transform/UseCounts.cpp
	backends/evm/ssa/transform/UseCounts.h
	backends/evm/ssa/traversal/ForwardTopologicalSort.cpp
	backends/evm/ssa/traversal/ForwardTopologicalSort.h
	optimiser/ASTCopier.cpp
	optimiser/ASTCopier.h
	optimiser/ASTWalker.cpp
	optimiser/ASTWalker.h
	optimiser/BlockFlattener.cpp
	optimiser/BlockFlattener.h
	optimiser/BlockHasher.cpp
	optimiser/BlockHasher.h
	optimiser/CallGraphGenerator.cpp
	optimiser/CallGraphGenerator.h
	optimiser/CircularReferencesPruner.cpp
	optimiser/CircularReferencesPruner.h
	optimiser/CommonSubexpressionEliminator.cpp
	optimiser/CommonSubexpressionEliminator.h
	optimiser/ConditionalSimplifier.cpp
	optimiser/ConditionalSimplifier.h
	optimiser/ConditionalUnsimplifier.cpp
	optimiser/ConditionalUnsimplifier.h
	optimiser/ControlFlowSimplifier.cpp
	optimiser/ControlFlowSimplifier.h
	optimiser/DataFlowAnalyzer.cpp
	optimiser/DataFlowAnalyzer.h
	optimiser/DeadCodeEliminator.cpp
	optimiser/DeadCodeEliminator.h
	optimiser/Disambiguator.cpp
	optimiser/Disambiguator.h
	optimiser/EqualStoreEliminator.cpp
	optimiser/EqualStoreEliminator.h
	optimiser/EquivalentFunctionDetector.cpp
	optimiser/EquivalentFunctionDetector.h
	optimiser/EquivalentFunctionCombiner.cpp
	optimiser/EquivalentFunctionCombiner.h
	optimiser/ExpressionInliner.cpp
	optimiser/ExpressionInliner.h
	optimiser/ExpressionJoiner.cpp
	optimiser/ExpressionJoiner.h
	optimiser/ExpressionSimplifier.cpp
	optimiser/ExpressionSimplifier.h
	optimiser/ExpressionSplitter.cpp
	optimiser/ExpressionSplitter.h
	optimiser/ForLoopConditionIntoBody.cpp
	optimiser/ForLoopConditionIntoBody.h
	optimiser/ForLoopConditionOutOfBody.cpp
	optimiser/ForLoopConditionOutOfBody.h
	optimiser/ForLoopInitRewriter.cpp
	optimiser/ForLoopInitRewriter.h
	optimiser/FullInliner.cpp
	optimiser/FullInliner.h
	optimiser/FunctionCallFinder.cpp
	optimiser/FunctionCallFinder.h
	optimiser/FunctionGrouper.cpp
	optimiser/FunctionGrouper.h
	optimiser/FunctionHoister.cpp
	optimiser/FunctionHoister.h
	optimiser/FunctionSpecializer.cpp
	optimiser/FunctionSpecializer.h
	optimiser/InlinableExpressionFunctionFinder.cpp
	optimiser/InlinableExpressionFunctionFinder.h
	optimiser/KnowledgeBase.cpp
	optimiser/KnowledgeBase.h
	optimiser/LabelIDDispenser.cpp
	optimiser/LabelIDDispenser.h
	optimiser/LoadResolver.cpp
	optimiser/LoadResolver.h
	optimiser/LoopInvariantCodeMotion.cpp
	optimiser/LoopInvariantCodeMotion.h
	optimiser/Metrics.cpp
	optimiser/Metrics.h
	optimiser/NameCollector.cpp
	optimiser/NameCollector.h
	optimiser/NameDispenser.cpp
	optimiser/NameDispenser.h
	optimiser/NameDisplacer.cpp
	optimiser/NameDisplacer.h
	optimiser/NameSimplifier.cpp
	optimiser/NameSimplifier.h
	optimiser/OptimiserStep.h
	optimiser/OptimizerUtilities.cpp
	optimiser/OptimizerUtilities.h
	optimiser/UnusedAssignEliminator.cpp
	optimiser/UnusedAssignEliminator.h
	optimiser/UnusedStoreBase.cpp
	optimiser/UnusedStoreBase.h
	optimiser/UnusedStoreEliminator.cpp
	optimiser/UnusedStoreEliminator.h
	optimiser/Rematerialiser.cpp
	optimiser/Rematerialiser.h
	optimiser/SSAReverser.cpp
	optimiser/SSAReverser.h
	optimiser/SSATransform.cpp
	optimiser/SSATransform.h
	optimiser/SSAValueTracker.cpp
	optimiser/SSAValueTracker.h
	optimiser/Semantics.cpp
	optimiser/Semantics.h
	optimiser/SimplificationRules.cpp
	optimiser/SimplificationRules.h
	optimiser/StackCompressor.cpp
	optimiser/StackCompressor.h
	optimiser/StackLimitEvader.cpp
	optimiser/StackLimitEvader.h
	optimiser/StackToMemoryMover.cpp
	optimiser/StackToMemoryMover.h
	optimiser/StructuralSimplifier.cpp
	optimiser/StructuralSimplifier.h
	optimiser/Substitution.cpp
	optimiser/Substitution.h
	optimiser/Suite.cpp
	optimiser/Suite.h
	optimiser/SyntacticalEquality.cpp
	optimiser/SyntacticalEquality.h
	optimiser/UnusedFunctionParameterPruner.cpp
	optimiser/UnusedFunctionParameterPruner.h
	optimiser/UnusedFunctionsCommon.h
	optimiser/UnusedFunctionsCommon.cpp
	optimiser/UnusedPruner.cpp
	optimiser/UnusedPruner.h
	optimiser/VarDeclInitializer.cpp
	optimiser/VarDeclInitializer.h
	optimiser/VarNameCleaner.cpp
	optimiser/VarNameCleaner.h
)

target_link_libraries(yul PUBLIC evmasm solutil langutil smtutil fmt::fmt-header-only)
