/*
# Test for all arithmetic operations
# This python script is used to generate the test
from itertools import product
import random

random.seed(20240823)

src = []
src.append('{')
src.append("""
    function check(a, b)
    { if iszero(eq(a, b)) { revert(0, 0) } }
""")

MX = 2**256
correct = lambda num: int(num) % MX
u2s = lambda num: int(num) - MX if (int(num) >> 255) > 0 else int(num)

def gen_test(fn_name, calc, param_cnt, nums = None):
    if nums is None:
        nums = [0, 1, 2, MX - 1, MX - 2, random.randrange(MX), random.randrange(MX)]
    param_set = list(product(nums, repeat=param_cnt))
    for i, p in enumerate(param_set):
        res = correct(calc(p))
        src.append(f'    function test_{fn_name}_{i}() {{ check({fn_name}({', '.join(str(i) for i in p)}), {res}) }}')
    src.append('')

gen_test('add', lambda p: p[0] + p[1], 2)
gen_test('mul', lambda p: p[0] * p[1], 2)
gen_test('sub', lambda p: p[0] - p[1], 2)
gen_test('div', lambda p: p[0] // p[1] if p[1] != 0 else 0, 2)
def sdiv(p):
    (a, b) = u2s(p[0]), u2s(p[1])
    if b == 0:
       return 0
    res = abs(a) // abs(b)
    if (a < 0) != (b < 0):
        res = -res
    return res
def smod(p):
    (a, b) = u2s(p[0]), u2s(p[1])
    if b == 0:
       return 0
    res = abs(a) % abs(b)
    if a < 0:
        res = -res
    return res
gen_test('sdiv', sdiv, 2)
gen_test('mod', lambda p: p[0] % p[1] if p[1] != 0 else 0, 2)
gen_test('smod', smod, 2)
gen_test('exp', lambda p: pow(p[0], p[1], MX), 2)
gen_test('not', lambda p: ~p[0], 1)
gen_test('lt', lambda p: p[0] < p[1], 2)
gen_test('gt', lambda p: p[0] > p[1], 2)
gen_test('slt', lambda p: u2s(p[0]) < u2s(p[1]), 2)
gen_test('sgt', lambda p: u2s(p[0]) > u2s(p[1]), 2)
gen_test('eq', lambda p: p[0] == p[1], 2)
gen_test('iszero', lambda p: p[0] == 0, 1)
gen_test('and', lambda p: p[0] & p[1], 2)
gen_test('or', lambda p: p[0] | p[1], 2)
gen_test('xor', lambda p: p[0] ^ p[1], 2)
gen_test('byte', lambda p: 0 if p[0] >= 32 else (p[1] >> (8 * (31 - p[0]))) & 0xff, 2,
         nums = [random.randrange(MX), random.randrange(MX), random.randrange(32), random.randrange(32), 0])
gen_test('shl', lambda p: p[1] << p[0] if p[0] < 32 else 0, 2)
gen_test('shr', lambda p: p[1] >> p[0], 2)
def sar(p):
    (sh, val) = p
    high_bit = val >> 255
    val >>= sh
    val |= correct(-high_bit) << max(0, 255 - sh)
    return val
gen_test('sar', sar, 2)
gen_test('addmod', lambda p: (p[0] + p[1]) % p[2] if p[2] != 0 else 0, 3,
         nums = [random.randrange(0, MX) for i in range(3)] + [0])
gen_test('mulmod', lambda p: (p[0] * p[1]) % p[2] if p[2] != 0 else 0, 3,
         nums = [random.randrange(0, MX) for i in range(3)] + [0])
def signextend(p):
    (byte_pos, val) = p
    byte_pos = min(byte_pos, 32)
    mask_shift = byte_pos * 8 + 8
    high_bit = (val >> (mask_shift - 1)) & 1
    if high_bit:
        return val | (correct(-1) << mask_shift)
    return val & ((1 << mask_shift) - 1)
gen_test('signextend', signextend, 2)

src.append('}')
print('\n'.join(src))
*/
{

    function check(a, b)
    { if iszero(eq(a, b)) { revert(0, 0) } }

    function test_add_0() { check(add(0, 0), 0) }
    function test_add_1() { check(add(0, 1), 1) }
    function test_add_2() { check(add(0, 2), 2) }
    function test_add_3() { check(add(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_add_4() { check(add(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_add_5() { check(add(0, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 22511778810690419408606032611692914343393218118973564305246125296861161142670) }
    function test_add_6() { check(add(0, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 19659681746644293860765529169101785554351274765820567770131372417486817992443) }
    function test_add_7() { check(add(1, 0), 1) }
    function test_add_8() { check(add(1, 1), 2) }
    function test_add_9() { check(add(1, 2), 3) }
    function test_add_10() { check(add(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_add_11() { check(add(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_add_12() { check(add(1, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 22511778810690419408606032611692914343393218118973564305246125296861161142671) }
    function test_add_13() { check(add(1, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 19659681746644293860765529169101785554351274765820567770131372417486817992444) }
    function test_add_14() { check(add(2, 0), 2) }
    function test_add_15() { check(add(2, 1), 3) }
    function test_add_16() { check(add(2, 2), 4) }
    function test_add_17() { check(add(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_add_18() { check(add(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_add_19() { check(add(2, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 22511778810690419408606032611692914343393218118973564305246125296861161142672) }
    function test_add_20() { check(add(2, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 19659681746644293860765529169101785554351274765820567770131372417486817992445) }
    function test_add_21() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_add_22() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_add_23() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 1) }
    function test_add_24() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_add_25() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_add_26() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 22511778810690419408606032611692914343393218118973564305246125296861161142669) }
    function test_add_27() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639935, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 19659681746644293860765529169101785554351274765820567770131372417486817992442) }
    function test_add_28() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_add_29() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_add_30() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_add_31() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_add_32() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_add_33() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 22511778810690419408606032611692914343393218118973564305246125296861161142668) }
    function test_add_34() { check(add(115792089237316195423570985008687907853269984665640564039457584007913129639934, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 19659681746644293860765529169101785554351274765820567770131372417486817992441) }
    function test_add_35() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 0), 22511778810690419408606032611692914343393218118973564305246125296861161142670) }
    function test_add_36() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 1), 22511778810690419408606032611692914343393218118973564305246125296861161142671) }
    function test_add_37() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 2), 22511778810690419408606032611692914343393218118973564305246125296861161142672) }
    function test_add_38() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 22511778810690419408606032611692914343393218118973564305246125296861161142669) }
    function test_add_39() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 22511778810690419408606032611692914343393218118973564305246125296861161142668) }
    function test_add_40() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 45023557621380838817212065223385828686786436237947128610492250593722322285340) }
    function test_add_41() { check(add(22511778810690419408606032611692914343393218118973564305246125296861161142670, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 42171460557334713269371561780794699897744492884794132075377497714347979135113) }
    function test_add_42() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 0), 19659681746644293860765529169101785554351274765820567770131372417486817992443) }
    function test_add_43() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 1), 19659681746644293860765529169101785554351274765820567770131372417486817992444) }
    function test_add_44() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 2), 19659681746644293860765529169101785554351274765820567770131372417486817992445) }
    function test_add_45() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 19659681746644293860765529169101785554351274765820567770131372417486817992442) }
    function test_add_46() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 19659681746644293860765529169101785554351274765820567770131372417486817992441) }
    function test_add_47() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 22511778810690419408606032611692914343393218118973564305246125296861161142670), 42171460557334713269371561780794699897744492884794132075377497714347979135113) }
    function test_add_48() { check(add(19659681746644293860765529169101785554351274765820567770131372417486817992443, 19659681746644293860765529169101785554351274765820567770131372417486817992443), 39319363493288587721531058338203571108702549531641135540262744834973635984886) }

    function test_mul_0() { check(mul(0, 0), 0) }
    function test_mul_1() { check(mul(0, 1), 0) }
    function test_mul_2() { check(mul(0, 2), 0) }
    function test_mul_3() { check(mul(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_mul_4() { check(mul(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_mul_5() { check(mul(0, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 0) }
    function test_mul_6() { check(mul(0, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 0) }
    function test_mul_7() { check(mul(1, 0), 0) }
    function test_mul_8() { check(mul(1, 1), 1) }
    function test_mul_9() { check(mul(1, 2), 2) }
    function test_mul_10() { check(mul(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_mul_11() { check(mul(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_mul_12() { check(mul(1, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 35257115525027604086735389276321862914110639864116864652044197398675076932980) }
    function test_mul_13() { check(mul(1, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 98159365508182072155166613423532953313337829988475134546938896051283252249466) }
    function test_mul_14() { check(mul(2, 0), 0) }
    function test_mul_15() { check(mul(2, 1), 2) }
    function test_mul_16() { check(mul(2, 2), 4) }
    function test_mul_17() { check(mul(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_mul_18() { check(mul(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_mul_19() { check(mul(2, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 70514231050055208173470778552643725828221279728233729304088394797350153865960) }
    function test_mul_20() { check(mul(2, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 80526641779047948886762241838377998773405675311309705054420208094653374858996) }
    function test_mul_21() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_mul_22() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_mul_23() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_mul_24() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_mul_25() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 2) }
    function test_mul_26() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 80534973712288591336835595732366044939159344801523699387413386609238052706956) }
    function test_mul_27() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639935, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 17632723729134123268404371585154954539932154677165429492518687956629877390470) }
    function test_mul_28() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_mul_29() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_mul_30() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_mul_31() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 2) }
    function test_mul_32() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 4) }
    function test_mul_33() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 45277858187260987250100206456044182025048704937406834735369189210562975773976) }
    function test_mul_34() { check(mul(115792089237316195423570985008687907853269984665640564039457584007913129639934, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 35265447458268246536808743170309909079864309354330858985037375913259754780940) }
    function test_mul_35() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 0), 0) }
    function test_mul_36() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 1), 35257115525027604086735389276321862914110639864116864652044197398675076932980) }
    function test_mul_37() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 2), 70514231050055208173470778552643725828221279728233729304088394797350153865960) }
    function test_mul_38() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 80534973712288591336835595732366044939159344801523699387413386609238052706956) }
    function test_mul_39() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 45277858187260987250100206456044182025048704937406834735369189210562975773976) }
    function test_mul_40() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 35676829315104958643211867670100128384171487943973514140263456863530508139664) }
    function test_mul_41() { check(mul(35257115525027604086735389276321862914110639864116864652044197398675076932980, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 36970967535082721992617999990656359956226150486086557968648561290405091325256) }
    function test_mul_42() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 0), 0) }
    function test_mul_43() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 1), 98159365508182072155166613423532953313337829988475134546938896051283252249466) }
    function test_mul_44() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 2), 80526641779047948886762241838377998773405675311309705054420208094653374858996) }
    function test_mul_45() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 17632723729134123268404371585154954539932154677165429492518687956629877390470) }
    function test_mul_46() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 35265447458268246536808743170309909079864309354330858985037375913259754780940) }
    function test_mul_47() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 35257115525027604086735389276321862914110639864116864652044197398675076932980), 36970967535082721992617999990656359956226150486086557968648561290405091325256) }
    function test_mul_48() { check(mul(98159365508182072155166613423532953313337829988475134546938896051283252249466, 98159365508182072155166613423532953313337829988475134546938896051283252249466), 42576009428253106427251274893516922021547438050651452850975486664461846451748) }

    function test_sub_0() { check(sub(0, 0), 0) }
    function test_sub_1() { check(sub(0, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sub_2() { check(sub(0, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sub_3() { check(sub(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_sub_4() { check(sub(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 2) }
    function test_sub_5() { check(sub(0, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 46463381287128400431974337525718804424694289887072529559313951359026832097612) }
    function test_sub_6() { check(sub(0, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 91422002387876264053805785317679062710509762754476634708324597678881636951274) }
    function test_sub_7() { check(sub(1, 0), 1) }
    function test_sub_8() { check(sub(1, 1), 0) }
    function test_sub_9() { check(sub(1, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sub_10() { check(sub(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 2) }
    function test_sub_11() { check(sub(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 3) }
    function test_sub_12() { check(sub(1, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 46463381287128400431974337525718804424694289887072529559313951359026832097613) }
    function test_sub_13() { check(sub(1, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 91422002387876264053805785317679062710509762754476634708324597678881636951275) }
    function test_sub_14() { check(sub(2, 0), 2) }
    function test_sub_15() { check(sub(2, 1), 1) }
    function test_sub_16() { check(sub(2, 2), 0) }
    function test_sub_17() { check(sub(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 3) }
    function test_sub_18() { check(sub(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 4) }
    function test_sub_19() { check(sub(2, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 46463381287128400431974337525718804424694289887072529559313951359026832097614) }
    function test_sub_20() { check(sub(2, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 91422002387876264053805785317679062710509762754476634708324597678881636951276) }
    function test_sub_21() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sub_22() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sub_23() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_sub_24() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sub_25() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sub_26() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 46463381287128400431974337525718804424694289887072529559313951359026832097611) }
    function test_sub_27() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639935, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 91422002387876264053805785317679062710509762754476634708324597678881636951273) }
    function test_sub_28() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sub_29() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_sub_30() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_sub_31() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sub_32() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sub_33() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 46463381287128400431974337525718804424694289887072529559313951359026832097610) }
    function test_sub_34() { check(sub(115792089237316195423570985008687907853269984665640564039457584007913129639934, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 91422002387876264053805785317679062710509762754476634708324597678881636951272) }
    function test_sub_35() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 0), 69328707950187794991596647482969103428575694778568034480143632648886297542324) }
    function test_sub_36() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 1), 69328707950187794991596647482969103428575694778568034480143632648886297542323) }
    function test_sub_37() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 2), 69328707950187794991596647482969103428575694778568034480143632648886297542322) }
    function test_sub_38() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 69328707950187794991596647482969103428575694778568034480143632648886297542325) }
    function test_sub_39() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 69328707950187794991596647482969103428575694778568034480143632648886297542326) }
    function test_sub_40() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 0) }
    function test_sub_41() { check(sub(69328707950187794991596647482969103428575694778568034480143632648886297542324, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 44958621100747863621831447791960258285815472867404105149010646319854804853662) }
    function test_sub_42() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 0), 24370086849439931369765199691008845142760221911163929331132986329031492688662) }
    function test_sub_43() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 1), 24370086849439931369765199691008845142760221911163929331132986329031492688661) }
    function test_sub_44() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 2), 24370086849439931369765199691008845142760221911163929331132986329031492688660) }
    function test_sub_45() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 24370086849439931369765199691008845142760221911163929331132986329031492688663) }
    function test_sub_46() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 24370086849439931369765199691008845142760221911163929331132986329031492688664) }
    function test_sub_47() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 69328707950187794991596647482969103428575694778568034480143632648886297542324), 70833468136568331801739537216727649567454511798236458890446937688058324786274) }
    function test_sub_48() { check(sub(24370086849439931369765199691008845142760221911163929331132986329031492688662, 24370086849439931369765199691008845142760221911163929331132986329031492688662), 0) }

    function test_div_0() { check(div(0, 0), 0) }
    function test_div_1() { check(div(0, 1), 0) }
    function test_div_2() { check(div(0, 2), 0) }
    function test_div_3() { check(div(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_4() { check(div(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_div_5() { check(div(0, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 0) }
    function test_div_6() { check(div(0, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 0) }
    function test_div_7() { check(div(1, 0), 0) }
    function test_div_8() { check(div(1, 1), 1) }
    function test_div_9() { check(div(1, 2), 0) }
    function test_div_10() { check(div(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_11() { check(div(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_div_12() { check(div(1, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 0) }
    function test_div_13() { check(div(1, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 0) }
    function test_div_14() { check(div(2, 0), 0) }
    function test_div_15() { check(div(2, 1), 2) }
    function test_div_16() { check(div(2, 2), 1) }
    function test_div_17() { check(div(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_18() { check(div(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_div_19() { check(div(2, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 0) }
    function test_div_20() { check(div(2, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 0) }
    function test_div_21() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_div_22() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_div_23() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 57896044618658097711785492504343953926634992332820282019728792003956564819967) }
    function test_div_24() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_div_25() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_div_26() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 5) }
    function test_div_27() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639935, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 19) }
    function test_div_28() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_div_29() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_div_30() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 57896044618658097711785492504343953926634992332820282019728792003956564819967) }
    function test_div_31() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_32() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_div_33() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 5) }
    function test_div_34() { check(div(115792089237316195423570985008687907853269984665640564039457584007913129639934, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 19) }
    function test_div_35() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 0), 0) }
    function test_div_36() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 1), 21527130834558241424046083922382403006195840439861643608969621269005030453628) }
    function test_div_37() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 2), 10763565417279120712023041961191201503097920219930821804484810634502515226814) }
    function test_div_38() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_39() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_div_40() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 1) }
    function test_div_41() { check(div(21527130834558241424046083922382403006195840439861643608969621269005030453628, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 3) }
    function test_div_42() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 0), 0) }
    function test_div_43() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 1), 5908159024281513356662484898389320596115702548129829256513866158551418012202) }
    function test_div_44() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 2), 2954079512140756678331242449194660298057851274064914628256933079275709006101) }
    function test_div_45() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_div_46() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_div_47() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 21527130834558241424046083922382403006195840439861643608969621269005030453628), 0) }
    function test_div_48() { check(div(5908159024281513356662484898389320596115702548129829256513866158551418012202, 5908159024281513356662484898389320596115702548129829256513866158551418012202), 1) }

    function test_sdiv_0() { check(sdiv(0, 0), 0) }
    function test_sdiv_1() { check(sdiv(0, 1), 0) }
    function test_sdiv_2() { check(sdiv(0, 2), 0) }
    function test_sdiv_3() { check(sdiv(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sdiv_4() { check(sdiv(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sdiv_5() { check(sdiv(0, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_6() { check(sdiv(0, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 0) }
    function test_sdiv_7() { check(sdiv(1, 0), 0) }
    function test_sdiv_8() { check(sdiv(1, 1), 1) }
    function test_sdiv_9() { check(sdiv(1, 2), 0) }
    function test_sdiv_10() { check(sdiv(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sdiv_11() { check(sdiv(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sdiv_12() { check(sdiv(1, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_13() { check(sdiv(1, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 0) }
    function test_sdiv_14() { check(sdiv(2, 0), 0) }
    function test_sdiv_15() { check(sdiv(2, 1), 2) }
    function test_sdiv_16() { check(sdiv(2, 2), 1) }
    function test_sdiv_17() { check(sdiv(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sdiv_18() { check(sdiv(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sdiv_19() { check(sdiv(2, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_20() { check(sdiv(2, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 0) }
    function test_sdiv_21() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_sdiv_22() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sdiv_23() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_sdiv_24() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_sdiv_25() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sdiv_26() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_27() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639935, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 0) }
    function test_sdiv_28() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_sdiv_29() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sdiv_30() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sdiv_31() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 2) }
    function test_sdiv_32() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sdiv_33() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_34() { check(sdiv(115792089237316195423570985008687907853269984665640564039457584007913129639934, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 0) }
    function test_sdiv_35() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 0), 0) }
    function test_sdiv_36() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 1), 69742936075047218892091269223170546483868182867646801161738300130733179999778) }
    function test_sdiv_37() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 2), 92767512656181707157831127115929227168569083766643682600597942069323154819857) }
    function test_sdiv_38() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 46049153162268976531479715785517361369401801797993762877719283877179949640158) }
    function test_sdiv_39() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 23024576581134488265739857892758680684700900898996881438859641938589974820079) }
    function test_sdiv_40() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 1) }
    function test_sdiv_41() { check(sdiv(69742936075047218892091269223170546483868182867646801161738300130733179999778, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sdiv_42() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 0), 0) }
    function test_sdiv_43() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 1), 41067838941032209417710089540241488427289292959688760797683786248366907217449) }
    function test_sdiv_44() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 2), 20533919470516104708855044770120744213644646479844380398841893124183453608724) }
    function test_sdiv_45() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 74724250296283986005860895468446419425980691705951803241773797759546222422487) }
    function test_sdiv_46() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 95258169766800090714715940238567163639625338185796183640615690883729676031212) }
    function test_sdiv_47() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 69742936075047218892091269223170546483868182867646801161738300130733179999778), 0) }
    function test_sdiv_48() { check(sdiv(41067838941032209417710089540241488427289292959688760797683786248366907217449, 41067838941032209417710089540241488427289292959688760797683786248366907217449), 1) }

    function test_mod_0() { check(mod(0, 0), 0) }
    function test_mod_1() { check(mod(0, 1), 0) }
    function test_mod_2() { check(mod(0, 2), 0) }
    function test_mod_3() { check(mod(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_mod_4() { check(mod(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_mod_5() { check(mod(0, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 0) }
    function test_mod_6() { check(mod(0, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 0) }
    function test_mod_7() { check(mod(1, 0), 0) }
    function test_mod_8() { check(mod(1, 1), 0) }
    function test_mod_9() { check(mod(1, 2), 1) }
    function test_mod_10() { check(mod(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_mod_11() { check(mod(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_mod_12() { check(mod(1, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 1) }
    function test_mod_13() { check(mod(1, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 1) }
    function test_mod_14() { check(mod(2, 0), 0) }
    function test_mod_15() { check(mod(2, 1), 0) }
    function test_mod_16() { check(mod(2, 2), 0) }
    function test_mod_17() { check(mod(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 2) }
    function test_mod_18() { check(mod(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 2) }
    function test_mod_19() { check(mod(2, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 2) }
    function test_mod_20() { check(mod(2, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 2) }
    function test_mod_21() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_mod_22() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_mod_23() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 1) }
    function test_mod_24() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_mod_25() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_mod_26() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 5316281849278187317149662917787059509109055571445510142082207305502987028944) }
    function test_mod_27() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 452544985399187085881578781266781892059920970368988619104258597157686629142) }
    function test_mod_28() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_mod_29() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_mod_30() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_mod_31() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_mod_32() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_mod_33() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 5316281849278187317149662917787059509109055571445510142082207305502987028943) }
    function test_mod_34() { check(mod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 452544985399187085881578781266781892059920970368988619104258597157686629141) }
    function test_mod_35() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 0), 0) }
    function test_mod_36() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 1), 0) }
    function test_mod_37() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 2), 1) }
    function test_mod_38() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 36825269129346002702140440696966949448053643031398351299125125567470047536997) }
    function test_mod_39() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 36825269129346002702140440696966949448053643031398351299125125567470047536997) }
    function test_mod_40() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 0) }
    function test_mod_41() { check(mod(36825269129346002702140440696966949448053643031398351299125125567470047536997, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 36825269129346002702140440696966949448053643031398351299125125567470047536997) }
    function test_mod_42() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 0), 0) }
    function test_mod_43() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 1), 0) }
    function test_mod_44() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 2), 1) }
    function test_mod_45() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115339544251917008337689406227421125961210063695271575420353325410755443010793) }
    function test_mod_46() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115339544251917008337689406227421125961210063695271575420353325410755443010793) }
    function test_mod_47() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 36825269129346002702140440696966949448053643031398351299125125567470047536997), 4863736863879000231268084136520277617049134601076521522977948708345300399802) }
    function test_mod_48() { check(mod(115339544251917008337689406227421125961210063695271575420353325410755443010793, 115339544251917008337689406227421125961210063695271575420353325410755443010793), 0) }

    function test_smod_0() { check(smod(0, 0), 0) }
    function test_smod_1() { check(smod(0, 1), 0) }
    function test_smod_2() { check(smod(0, 2), 0) }
    function test_smod_3() { check(smod(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_4() { check(smod(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_smod_5() { check(smod(0, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 0) }
    function test_smod_6() { check(smod(0, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 0) }
    function test_smod_7() { check(smod(1, 0), 0) }
    function test_smod_8() { check(smod(1, 1), 0) }
    function test_smod_9() { check(smod(1, 2), 1) }
    function test_smod_10() { check(smod(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_11() { check(smod(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_smod_12() { check(smod(1, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 1) }
    function test_smod_13() { check(smod(1, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 1) }
    function test_smod_14() { check(smod(2, 0), 0) }
    function test_smod_15() { check(smod(2, 1), 0) }
    function test_smod_16() { check(smod(2, 2), 0) }
    function test_smod_17() { check(smod(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_18() { check(smod(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_smod_19() { check(smod(2, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 2) }
    function test_smod_20() { check(smod(2, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 2) }
    function test_smod_21() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_smod_22() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_smod_23() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_smod_24() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_25() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_smod_26() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_smod_27() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639935, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_smod_28() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_smod_29() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_smod_30() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_smod_31() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_32() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_smod_33() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_smod_34() { check(smod(115792089237316195423570985008687907853269984665640564039457584007913129639934, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_smod_35() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 0), 0) }
    function test_smod_36() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 1), 0) }
    function test_smod_37() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 2), 0) }
    function test_smod_38() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_39() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_smod_40() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 0) }
    function test_smod_41() { check(smod(64228277382660959385678659397297888838796724718273788882560561403552036615880, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 109152371032138505310517293256569258499663668323505028350197431219202250267296) }
    function test_smod_42() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 0), 0) }
    function test_smod_43() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 1), 0) }
    function test_smod_44() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 2), 0) }
    function test_smod_45() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_smod_46() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_smod_47() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 64228277382660959385678659397297888838796724718273788882560561403552036615880), 11231023412369386481209658464817842415216735901307809866909217453912553412854) }
    function test_smod_48() { check(smod(11231023412369386481209658464817842415216735901307809866909217453912553412854, 11231023412369386481209658464817842415216735901307809866909217453912553412854), 0) }

    function test_exp_0() { check(exp(0, 0), 1) }
    function test_exp_1() { check(exp(0, 1), 0) }
    function test_exp_2() { check(exp(0, 2), 0) }
    function test_exp_3() { check(exp(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_exp_4() { check(exp(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_exp_5() { check(exp(0, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 0) }
    function test_exp_6() { check(exp(0, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 0) }
    function test_exp_7() { check(exp(1, 0), 1) }
    function test_exp_8() { check(exp(1, 1), 1) }
    function test_exp_9() { check(exp(1, 2), 1) }
    function test_exp_10() { check(exp(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_exp_11() { check(exp(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_exp_12() { check(exp(1, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 1) }
    function test_exp_13() { check(exp(1, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 1) }
    function test_exp_14() { check(exp(2, 0), 1) }
    function test_exp_15() { check(exp(2, 1), 2) }
    function test_exp_16() { check(exp(2, 2), 4) }
    function test_exp_17() { check(exp(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_exp_18() { check(exp(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_exp_19() { check(exp(2, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 0) }
    function test_exp_20() { check(exp(2, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 0) }
    function test_exp_21() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 1) }
    function test_exp_22() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_exp_23() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 1) }
    function test_exp_24() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_exp_25() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_exp_26() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_exp_27() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639935, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_exp_28() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 1) }
    function test_exp_29() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_exp_30() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 4) }
    function test_exp_31() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_exp_32() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_exp_33() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 0) }
    function test_exp_34() { check(exp(115792089237316195423570985008687907853269984665640564039457584007913129639934, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 0) }
    function test_exp_35() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 0), 1) }
    function test_exp_36() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 1), 115606902495168972315160449655162341994866798924771584142720835885133537129445) }
    function test_exp_37() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 2), 23719124936793778787876450117902569082795971420513865216479393835795806554841) }
    function test_exp_38() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 40077435397855390836825829047757859765238414361240355516876051624770643710445) }
    function test_exp_39() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 108018297088060445130926345359121830451934077009303250000327948703101226046825) }
    function test_exp_40() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 97150176448040565727269074697933552528659003146295560980491637979805214122005) }
    function test_exp_41() { check(exp(115606902495168972315160449655162341994866798924771584142720835885133537129445, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 63358729398289627527967434598672713318067733667214043023762601771700435621285) }
    function test_exp_42() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 0), 1) }
    function test_exp_43() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 1), 19016261866151635774443021074930362432861748244973906639398305101420816084945) }
    function test_exp_44() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 2), 74629681937752970613802439118038709119917259182873429909121362607996709464225) }
    function test_exp_45() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 30875495003004957983394972392970070081260406891337042524514781601031749044529) }
    function test_exp_46() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 7245849415207858963256606107610157872497234520555544843931569622001395596129) }
    function test_exp_47() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 115606902495168972315160449655162341994866798924771584142720835885133537129445), 68328571329938115399471929321299300586050922973827035291387941781230319771409) }
    function test_exp_48() { check(exp(19016261866151635774443021074930362432861748244973906639398305101420816084945, 19016261866151635774443021074930362432861748244973906639398305101420816084945), 89263219627053286008899524636370743314879091745423913331931537459307182940369) }

    function test_not_0() { check(not(0), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_not_1() { check(not(1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_not_2() { check(not(2), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_not_3() { check(not(115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_not_4() { check(not(115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_not_5() { check(not(5922964590783609873462582049084778189530164370652172856804360227125864711206), 109869124646532585550108402959603129663739820294988391182653223780787264928729) }
    function test_not_6() { check(not(37453707075031683597309133012068767151672171590489110276720091032418434326653), 78338382162284511826261851996619140701597813075151453762737492975494695313282) }

    function test_lt_0() { check(lt(0, 0), 0) }
    function test_lt_1() { check(lt(0, 1), 1) }
    function test_lt_2() { check(lt(0, 2), 1) }
    function test_lt_3() { check(lt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_4() { check(lt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_lt_5() { check(lt(0, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 1) }
    function test_lt_6() { check(lt(0, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 1) }
    function test_lt_7() { check(lt(1, 0), 0) }
    function test_lt_8() { check(lt(1, 1), 0) }
    function test_lt_9() { check(lt(1, 2), 1) }
    function test_lt_10() { check(lt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_11() { check(lt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_lt_12() { check(lt(1, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 1) }
    function test_lt_13() { check(lt(1, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 1) }
    function test_lt_14() { check(lt(2, 0), 0) }
    function test_lt_15() { check(lt(2, 1), 0) }
    function test_lt_16() { check(lt(2, 2), 0) }
    function test_lt_17() { check(lt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_18() { check(lt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_lt_19() { check(lt(2, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 1) }
    function test_lt_20() { check(lt(2, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 1) }
    function test_lt_21() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_lt_22() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_lt_23() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_lt_24() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_lt_25() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_lt_26() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 0) }
    function test_lt_27() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 0) }
    function test_lt_28() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_lt_29() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_lt_30() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_lt_31() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_32() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_lt_33() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 0) }
    function test_lt_34() { check(lt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 0) }
    function test_lt_35() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 0), 0) }
    function test_lt_36() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 1), 0) }
    function test_lt_37() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 2), 0) }
    function test_lt_38() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_39() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_lt_40() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 0) }
    function test_lt_41() { check(lt(110099802025650408331279406388138829088765583113642367910599120993463250367070, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 0) }
    function test_lt_42() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 0), 0) }
    function test_lt_43() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 1), 0) }
    function test_lt_44() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 2), 0) }
    function test_lt_45() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_lt_46() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_lt_47() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 110099802025650408331279406388138829088765583113642367910599120993463250367070), 1) }
    function test_lt_48() { check(lt(6989250744444949917814004474653212484134937610735153631554990646243336399660, 6989250744444949917814004474653212484134937610735153631554990646243336399660), 0) }

    function test_gt_0() { check(gt(0, 0), 0) }
    function test_gt_1() { check(gt(0, 1), 0) }
    function test_gt_2() { check(gt(0, 2), 0) }
    function test_gt_3() { check(gt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_4() { check(gt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_5() { check(gt(0, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 0) }
    function test_gt_6() { check(gt(0, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 0) }
    function test_gt_7() { check(gt(1, 0), 1) }
    function test_gt_8() { check(gt(1, 1), 0) }
    function test_gt_9() { check(gt(1, 2), 0) }
    function test_gt_10() { check(gt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_11() { check(gt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_12() { check(gt(1, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 0) }
    function test_gt_13() { check(gt(1, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 0) }
    function test_gt_14() { check(gt(2, 0), 1) }
    function test_gt_15() { check(gt(2, 1), 1) }
    function test_gt_16() { check(gt(2, 2), 0) }
    function test_gt_17() { check(gt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_18() { check(gt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_19() { check(gt(2, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 0) }
    function test_gt_20() { check(gt(2, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 0) }
    function test_gt_21() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 1) }
    function test_gt_22() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 1) }
    function test_gt_23() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 1) }
    function test_gt_24() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_25() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_gt_26() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 1) }
    function test_gt_27() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 1) }
    function test_gt_28() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 1) }
    function test_gt_29() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 1) }
    function test_gt_30() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 1) }
    function test_gt_31() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_32() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_33() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 1) }
    function test_gt_34() { check(gt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 1) }
    function test_gt_35() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 0), 1) }
    function test_gt_36() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 1), 1) }
    function test_gt_37() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 2), 1) }
    function test_gt_38() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_39() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_40() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 0) }
    function test_gt_41() { check(gt(72753833581632480403581180800177515552830775683493556930395600007729054862025, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 1) }
    function test_gt_42() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 0), 1) }
    function test_gt_43() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 1), 1) }
    function test_gt_44() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 2), 1) }
    function test_gt_45() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_gt_46() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_gt_47() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 72753833581632480403581180800177515552830775683493556930395600007729054862025), 0) }
    function test_gt_48() { check(gt(35494539573573499949677027375126255854449863281693517184786462304148614611354, 35494539573573499949677027375126255854449863281693517184786462304148614611354), 0) }

    function test_slt_0() { check(slt(0, 0), 0) }
    function test_slt_1() { check(slt(0, 1), 1) }
    function test_slt_2() { check(slt(0, 2), 1) }
    function test_slt_3() { check(slt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_slt_4() { check(slt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_5() { check(slt(0, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_6() { check(slt(0, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_7() { check(slt(1, 0), 0) }
    function test_slt_8() { check(slt(1, 1), 0) }
    function test_slt_9() { check(slt(1, 2), 1) }
    function test_slt_10() { check(slt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_slt_11() { check(slt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_12() { check(slt(1, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_13() { check(slt(1, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_14() { check(slt(2, 0), 0) }
    function test_slt_15() { check(slt(2, 1), 0) }
    function test_slt_16() { check(slt(2, 2), 0) }
    function test_slt_17() { check(slt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_slt_18() { check(slt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_19() { check(slt(2, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_20() { check(slt(2, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_21() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 1) }
    function test_slt_22() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 1) }
    function test_slt_23() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 1) }
    function test_slt_24() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_slt_25() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_26() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_27() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_28() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 1) }
    function test_slt_29() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 1) }
    function test_slt_30() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 1) }
    function test_slt_31() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_slt_32() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_33() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_34() { check(slt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_35() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 0), 1) }
    function test_slt_36() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 1), 1) }
    function test_slt_37() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 2), 1) }
    function test_slt_38() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_slt_39() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_slt_40() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_41() { check(slt(68017881531202612655098452160630207043010425238896656775011886183092720945596, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 1) }
    function test_slt_42() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 0), 0) }
    function test_slt_43() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 1), 0) }
    function test_slt_44() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 2), 0) }
    function test_slt_45() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_slt_46() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_slt_47() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 68017881531202612655098452160630207043010425238896656775011886183092720945596), 0) }
    function test_slt_48() { check(slt(13258081525883010947558584854410285822447126715354520153946626756711423178387, 13258081525883010947558584854410285822447126715354520153946626756711423178387), 0) }

    function test_sgt_0() { check(sgt(0, 0), 0) }
    function test_sgt_1() { check(sgt(0, 1), 0) }
    function test_sgt_2() { check(sgt(0, 2), 0) }
    function test_sgt_3() { check(sgt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_sgt_4() { check(sgt(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sgt_5() { check(sgt(0, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_6() { check(sgt(0, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 1) }
    function test_sgt_7() { check(sgt(1, 0), 1) }
    function test_sgt_8() { check(sgt(1, 1), 0) }
    function test_sgt_9() { check(sgt(1, 2), 0) }
    function test_sgt_10() { check(sgt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_sgt_11() { check(sgt(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sgt_12() { check(sgt(1, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_13() { check(sgt(1, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 1) }
    function test_sgt_14() { check(sgt(2, 0), 1) }
    function test_sgt_15() { check(sgt(2, 1), 1) }
    function test_sgt_16() { check(sgt(2, 2), 0) }
    function test_sgt_17() { check(sgt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_sgt_18() { check(sgt(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sgt_19() { check(sgt(2, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_20() { check(sgt(2, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 1) }
    function test_sgt_21() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_sgt_22() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_sgt_23() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_sgt_24() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sgt_25() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_sgt_26() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_27() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639935, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 1) }
    function test_sgt_28() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_sgt_29() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_sgt_30() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_sgt_31() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sgt_32() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sgt_33() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_34() { check(sgt(115792089237316195423570985008687907853269984665640564039457584007913129639934, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 1) }
    function test_sgt_35() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 0), 0) }
    function test_sgt_36() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 1), 0) }
    function test_sgt_37() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 2), 0) }
    function test_sgt_38() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sgt_39() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sgt_40() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 0) }
    function test_sgt_41() { check(sgt(84035909357050252967004801141438404926957547641310423814578084074734573169278, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 0) }
    function test_sgt_42() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 0), 0) }
    function test_sgt_43() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 1), 0) }
    function test_sgt_44() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 2), 0) }
    function test_sgt_45() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_sgt_46() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_sgt_47() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 84035909357050252967004801141438404926957547641310423814578084074734573169278), 1) }
    function test_sgt_48() { check(sgt(103576254108133286169029693563110491732386143024483320278410864238899725331915, 103576254108133286169029693563110491732386143024483320278410864238899725331915), 0) }

    function test_eq_0() { check(eq(0, 0), 1) }
    function test_eq_1() { check(eq(0, 1), 0) }
    function test_eq_2() { check(eq(0, 2), 0) }
    function test_eq_3() { check(eq(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_4() { check(eq(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_5() { check(eq(0, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_6() { check(eq(0, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_7() { check(eq(1, 0), 0) }
    function test_eq_8() { check(eq(1, 1), 1) }
    function test_eq_9() { check(eq(1, 2), 0) }
    function test_eq_10() { check(eq(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_11() { check(eq(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_12() { check(eq(1, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_13() { check(eq(1, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_14() { check(eq(2, 0), 0) }
    function test_eq_15() { check(eq(2, 1), 0) }
    function test_eq_16() { check(eq(2, 2), 1) }
    function test_eq_17() { check(eq(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_18() { check(eq(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_19() { check(eq(2, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_20() { check(eq(2, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_21() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_eq_22() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_eq_23() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_eq_24() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_eq_25() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_26() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_27() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639935, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_28() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_eq_29() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_eq_30() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_eq_31() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_32() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_eq_33() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_34() { check(eq(115792089237316195423570985008687907853269984665640564039457584007913129639934, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_35() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 0), 0) }
    function test_eq_36() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 1), 0) }
    function test_eq_37() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 2), 0) }
    function test_eq_38() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_39() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_40() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 1) }
    function test_eq_41() { check(eq(97133802217059873572115247499120430778873647836906735131740627443945036049230, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 0) }
    function test_eq_42() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 0), 0) }
    function test_eq_43() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 1), 0) }
    function test_eq_44() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 2), 0) }
    function test_eq_45() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_eq_46() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_eq_47() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 97133802217059873572115247499120430778873647836906735131740627443945036049230), 0) }
    function test_eq_48() { check(eq(103127332497177868134427090381050163513970449586554649944836964578763488208973, 103127332497177868134427090381050163513970449586554649944836964578763488208973), 1) }

    function test_iszero_0() { check(iszero(0), 1) }
    function test_iszero_1() { check(iszero(1), 0) }
    function test_iszero_2() { check(iszero(2), 0) }
    function test_iszero_3() { check(iszero(115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_iszero_4() { check(iszero(115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_iszero_5() { check(iszero(78747297409364612785885845379455161720601848466564928756860453014835669881157), 0) }
    function test_iszero_6() { check(iszero(9557482626947878892720236566563598074546921018893965976656816169955093186136), 0) }

    function test_and_0() { check(and(0, 0), 0) }
    function test_and_1() { check(and(0, 1), 0) }
    function test_and_2() { check(and(0, 2), 0) }
    function test_and_3() { check(and(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_and_4() { check(and(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_and_5() { check(and(0, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 0) }
    function test_and_6() { check(and(0, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 0) }
    function test_and_7() { check(and(1, 0), 0) }
    function test_and_8() { check(and(1, 1), 1) }
    function test_and_9() { check(and(1, 2), 0) }
    function test_and_10() { check(and(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_and_11() { check(and(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_and_12() { check(and(1, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 1) }
    function test_and_13() { check(and(1, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 0) }
    function test_and_14() { check(and(2, 0), 0) }
    function test_and_15() { check(and(2, 1), 0) }
    function test_and_16() { check(and(2, 2), 2) }
    function test_and_17() { check(and(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 2) }
    function test_and_18() { check(and(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 2) }
    function test_and_19() { check(and(2, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 2) }
    function test_and_20() { check(and(2, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 0) }
    function test_and_21() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_and_22() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 1) }
    function test_and_23() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 2) }
    function test_and_24() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_and_25() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_and_26() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 19250563356642585679821982809780683800151980259572704592519096096056450665275) }
    function test_and_27() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639935, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 46417999922850358461056893659186219261610420503262663932694263891945069455012) }
    function test_and_28() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_and_29() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_and_30() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 2) }
    function test_and_31() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_and_32() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_and_33() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 19250563356642585679821982809780683800151980259572704592519096096056450665274) }
    function test_and_34() { check(and(115792089237316195423570985008687907853269984665640564039457584007913129639934, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 46417999922850358461056893659186219261610420503262663932694263891945069455012) }
    function test_and_35() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 0), 0) }
    function test_and_36() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 1), 1) }
    function test_and_37() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 2), 2) }
    function test_and_38() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 19250563356642585679821982809780683800151980259572704592519096096056450665275) }
    function test_and_39() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 19250563356642585679821982809780683800151980259572704592519096096056450665274) }
    function test_and_40() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 19250563356642585679821982809780683800151980259572704592519096096056450665275) }
    function test_and_41() { check(and(19250563356642585679821982809780683800151980259572704592519096096056450665275, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 15631572267631210243224111594511664554898671681708678689198934479333455725088) }
    function test_and_42() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 0), 0) }
    function test_and_43() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 1), 0) }
    function test_and_44() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 2), 0) }
    function test_and_45() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 46417999922850358461056893659186219261610420503262663932694263891945069455012) }
    function test_and_46() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 46417999922850358461056893659186219261610420503262663932694263891945069455012) }
    function test_and_47() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 19250563356642585679821982809780683800151980259572704592519096096056450665275), 15631572267631210243224111594511664554898671681708678689198934479333455725088) }
    function test_and_48() { check(and(46417999922850358461056893659186219261610420503262663932694263891945069455012, 46417999922850358461056893659186219261610420503262663932694263891945069455012), 46417999922850358461056893659186219261610420503262663932694263891945069455012) }

    function test_or_0() { check(or(0, 0), 0) }
    function test_or_1() { check(or(0, 1), 1) }
    function test_or_2() { check(or(0, 2), 2) }
    function test_or_3() { check(or(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_4() { check(or(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_5() { check(or(0, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 56958862471241653073072976553386602741495522157520644114395302660506026208404) }
    function test_or_6() { check(or(0, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_7() { check(or(1, 0), 1) }
    function test_or_8() { check(or(1, 1), 1) }
    function test_or_9() { check(or(1, 2), 3) }
    function test_or_10() { check(or(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_11() { check(or(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_12() { check(or(1, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 56958862471241653073072976553386602741495522157520644114395302660506026208405) }
    function test_or_13() { check(or(1, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_14() { check(or(2, 0), 2) }
    function test_or_15() { check(or(2, 1), 3) }
    function test_or_16() { check(or(2, 2), 2) }
    function test_or_17() { check(or(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_18() { check(or(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_19() { check(or(2, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 56958862471241653073072976553386602741495522157520644114395302660506026208406) }
    function test_or_20() { check(or(2, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_21() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_22() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_23() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_24() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_25() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_26() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_27() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639935, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_28() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_29() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_30() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_31() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_32() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_33() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_34() { check(or(115792089237316195423570985008687907853269984665640564039457584007913129639934, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_35() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 0), 56958862471241653073072976553386602741495522157520644114395302660506026208404) }
    function test_or_36() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 1), 56958862471241653073072976553386602741495522157520644114395302660506026208405) }
    function test_or_37() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 2), 56958862471241653073072976553386602741495522157520644114395302660506026208406) }
    function test_or_38() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_39() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_or_40() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 56958862471241653073072976553386602741495522157520644114395302660506026208404) }
    function test_or_41() { check(or(56958862471241653073072976553386602741495522157520644114395302660506026208404, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 57895513161191823138089177244917758114200981566710351315321107400068061200063) }
    function test_or_42() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 0), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_43() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 1), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_44() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 2), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }
    function test_or_45() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_46() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_or_47() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 56958862471241653073072976553386602741495522157520644114395302660506026208404), 57895513161191823138089177244917758114200981566710351315321107400068061200063) }
    function test_or_48() { check(or(41540679175160398463199353554771824285248731067717774369911027068229334053563, 41540679175160398463199353554771824285248731067717774369911027068229334053563), 41540679175160398463199353554771824285248731067717774369911027068229334053563) }

    function test_xor_0() { check(xor(0, 0), 0) }
    function test_xor_1() { check(xor(0, 1), 1) }
    function test_xor_2() { check(xor(0, 2), 2) }
    function test_xor_3() { check(xor(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_xor_4() { check(xor(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_xor_5() { check(xor(0, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 93879730722178485205967128194645854796186255569129730504744197411393305498348) }
    function test_xor_6() { check(xor(0, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 14232531272672338704119765390482207930099023516624419694095745480866891788086) }
    function test_xor_7() { check(xor(1, 0), 1) }
    function test_xor_8() { check(xor(1, 1), 0) }
    function test_xor_9() { check(xor(1, 2), 3) }
    function test_xor_10() { check(xor(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_xor_11() { check(xor(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_xor_12() { check(xor(1, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 93879730722178485205967128194645854796186255569129730504744197411393305498349) }
    function test_xor_13() { check(xor(1, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 14232531272672338704119765390482207930099023516624419694095745480866891788087) }
    function test_xor_14() { check(xor(2, 0), 2) }
    function test_xor_15() { check(xor(2, 1), 3) }
    function test_xor_16() { check(xor(2, 2), 0) }
    function test_xor_17() { check(xor(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_xor_18() { check(xor(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_xor_19() { check(xor(2, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 93879730722178485205967128194645854796186255569129730504744197411393305498350) }
    function test_xor_20() { check(xor(2, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 14232531272672338704119765390482207930099023516624419694095745480866891788084) }
    function test_xor_21() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_xor_22() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_xor_23() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639933) }
    function test_xor_24() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_xor_25() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 1) }
    function test_xor_26() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 21912358515137710217603856814042053057083729096510833534713386596519824141587) }
    function test_xor_27() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639935, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 101559557964643856719451219618205699923170961149016144345361838527046237851849) }
    function test_xor_28() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_xor_29() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_xor_30() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_xor_31() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 1) }
    function test_xor_32() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_xor_33() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 21912358515137710217603856814042053057083729096510833534713386596519824141586) }
    function test_xor_34() { check(xor(115792089237316195423570985008687907853269984665640564039457584007913129639934, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 101559557964643856719451219618205699923170961149016144345361838527046237851848) }
    function test_xor_35() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 0), 93879730722178485205967128194645854796186255569129730504744197411393305498348) }
    function test_xor_36() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 1), 93879730722178485205967128194645854796186255569129730504744197411393305498349) }
    function test_xor_37() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 2), 93879730722178485205967128194645854796186255569129730504744197411393305498350) }
    function test_xor_38() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 21912358515137710217603856814042053057083729096510833534713386596519824141587) }
    function test_xor_39() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 21912358515137710217603856814042053057083729096510833534713386596519824141586) }
    function test_xor_40() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 0) }
    function test_xor_41() { check(xor(93879730722178485205967128194645854796186255569129730504744197411393305498348, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 94521629507852507853109237600535852707402170726003012251761205963601127259610) }
    function test_xor_42() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 0), 14232531272672338704119765390482207930099023516624419694095745480866891788086) }
    function test_xor_43() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 1), 14232531272672338704119765390482207930099023516624419694095745480866891788087) }
    function test_xor_44() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 2), 14232531272672338704119765390482207930099023516624419694095745480866891788084) }
    function test_xor_45() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 101559557964643856719451219618205699923170961149016144345361838527046237851849) }
    function test_xor_46() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 101559557964643856719451219618205699923170961149016144345361838527046237851848) }
    function test_xor_47() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 93879730722178485205967128194645854796186255569129730504744197411393305498348), 94521629507852507853109237600535852707402170726003012251761205963601127259610) }
    function test_xor_48() { check(xor(14232531272672338704119765390482207930099023516624419694095745480866891788086, 14232531272672338704119765390482207930099023516624419694095745480866891788086), 0) }

    function test_byte_0() { check(byte(68800988322768072237345063627670221053112791386522147760437104509587064083236, 68800988322768072237345063627670221053112791386522147760437104509587064083236), 0) }
    function test_byte_1() { check(byte(68800988322768072237345063627670221053112791386522147760437104509587064083236, 87594912600945758326410424914523594146731054887000169625869931741457929600180), 0) }
    function test_byte_2() { check(byte(68800988322768072237345063627670221053112791386522147760437104509587064083236, 30), 0) }
    function test_byte_3() { check(byte(68800988322768072237345063627670221053112791386522147760437104509587064083236, 26), 0) }
    function test_byte_4() { check(byte(68800988322768072237345063627670221053112791386522147760437104509587064083236, 0), 0) }
    function test_byte_5() { check(byte(87594912600945758326410424914523594146731054887000169625869931741457929600180, 68800988322768072237345063627670221053112791386522147760437104509587064083236), 0) }
    function test_byte_6() { check(byte(87594912600945758326410424914523594146731054887000169625869931741457929600180, 87594912600945758326410424914523594146731054887000169625869931741457929600180), 0) }
    function test_byte_7() { check(byte(87594912600945758326410424914523594146731054887000169625869931741457929600180, 30), 0) }
    function test_byte_8() { check(byte(87594912600945758326410424914523594146731054887000169625869931741457929600180, 26), 0) }
    function test_byte_9() { check(byte(87594912600945758326410424914523594146731054887000169625869931741457929600180, 0), 0) }
    function test_byte_10() { check(byte(30, 68800988322768072237345063627670221053112791386522147760437104509587064083236), 211) }
    function test_byte_11() { check(byte(30, 87594912600945758326410424914523594146731054887000169625869931741457929600180), 252) }
    function test_byte_12() { check(byte(30, 30), 0) }
    function test_byte_13() { check(byte(30, 26), 0) }
    function test_byte_14() { check(byte(30, 0), 0) }
    function test_byte_15() { check(byte(26, 68800988322768072237345063627670221053112791386522147760437104509587064083236), 82) }
    function test_byte_16() { check(byte(26, 87594912600945758326410424914523594146731054887000169625869931741457929600180), 233) }
    function test_byte_17() { check(byte(26, 30), 0) }
    function test_byte_18() { check(byte(26, 26), 0) }
    function test_byte_19() { check(byte(26, 0), 0) }
    function test_byte_20() { check(byte(0, 68800988322768072237345063627670221053112791386522147760437104509587064083236), 152) }
    function test_byte_21() { check(byte(0, 87594912600945758326410424914523594146731054887000169625869931741457929600180), 193) }
    function test_byte_22() { check(byte(0, 30), 0) }
    function test_byte_23() { check(byte(0, 26), 0) }
    function test_byte_24() { check(byte(0, 0), 0) }

    function test_shl_0() { check(shl(0, 0), 0) }
    function test_shl_1() { check(shl(0, 1), 1) }
    function test_shl_2() { check(shl(0, 2), 2) }
    function test_shl_3() { check(shl(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_shl_4() { check(shl(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_shl_5() { check(shl(0, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 44264216052681650963313079231923757121479731937092683747356446748236073468430) }
    function test_shl_6() { check(shl(0, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 31375775438714370564795450075197198747006289363524780583775597123749079718168) }
    function test_shl_7() { check(shl(1, 0), 0) }
    function test_shl_8() { check(shl(1, 1), 2) }
    function test_shl_9() { check(shl(1, 2), 4) }
    function test_shl_10() { check(shl(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_shl_11() { check(shl(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_shl_12() { check(shl(1, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 88528432105363301926626158463847514242959463874185367494712893496472146936860) }
    function test_shl_13() { check(shl(1, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 62751550877428741129590900150394397494012578727049561167551194247498159436336) }
    function test_shl_14() { check(shl(2, 0), 0) }
    function test_shl_15() { check(shl(2, 1), 4) }
    function test_shl_16() { check(shl(2, 2), 8) }
    function test_shl_17() { check(shl(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639932) }
    function test_shl_18() { check(shl(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639928) }
    function test_shl_19() { check(shl(2, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 61264774973410408429681331919007120632648943082730170949968202985031164233784) }
    function test_shl_20() { check(shl(2, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 9711012517541286835610815292100887134755172788458558295644804487083189232736) }
    function test_shl_21() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_shl_22() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_shl_23() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_shl_24() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shl_25() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shl_26() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 0) }
    function test_shl_27() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639935, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 0) }
    function test_shl_28() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_shl_29() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_shl_30() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_shl_31() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shl_32() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shl_33() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 0) }
    function test_shl_34() { check(shl(115792089237316195423570985008687907853269984665640564039457584007913129639934, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 0) }
    function test_shl_35() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 0), 0) }
    function test_shl_36() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 1), 0) }
    function test_shl_37() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 2), 0) }
    function test_shl_38() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shl_39() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shl_40() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 0) }
    function test_shl_41() { check(shl(44264216052681650963313079231923757121479731937092683747356446748236073468430, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 0) }
    function test_shl_42() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 0), 0) }
    function test_shl_43() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 1), 0) }
    function test_shl_44() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 2), 0) }
    function test_shl_45() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shl_46() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shl_47() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 44264216052681650963313079231923757121479731937092683747356446748236073468430), 0) }
    function test_shl_48() { check(shl(31375775438714370564795450075197198747006289363524780583775597123749079718168, 31375775438714370564795450075197198747006289363524780583775597123749079718168), 0) }

    function test_shr_0() { check(shr(0, 0), 0) }
    function test_shr_1() { check(shr(0, 1), 1) }
    function test_shr_2() { check(shr(0, 2), 2) }
    function test_shr_3() { check(shr(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_shr_4() { check(shr(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_shr_5() { check(shr(0, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 37274857428727835743259556673680271738176590670119373800342835673791532889898) }
    function test_shr_6() { check(shr(0, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 62702957303074580081337476767887907527881951999783234736971020740941246311273) }
    function test_shr_7() { check(shr(1, 0), 0) }
    function test_shr_8() { check(shr(1, 1), 0) }
    function test_shr_9() { check(shr(1, 2), 1) }
    function test_shr_10() { check(shr(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 57896044618658097711785492504343953926634992332820282019728792003956564819967) }
    function test_shr_11() { check(shr(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 57896044618658097711785492504343953926634992332820282019728792003956564819967) }
    function test_shr_12() { check(shr(1, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 18637428714363917871629778336840135869088295335059686900171417836895766444949) }
    function test_shr_13() { check(shr(1, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 31351478651537290040668738383943953763940975999891617368485510370470623155636) }
    function test_shr_14() { check(shr(2, 0), 0) }
    function test_shr_15() { check(shr(2, 1), 0) }
    function test_shr_16() { check(shr(2, 2), 0) }
    function test_shr_17() { check(shr(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 28948022309329048855892746252171976963317496166410141009864396001978282409983) }
    function test_shr_18() { check(shr(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 28948022309329048855892746252171976963317496166410141009864396001978282409983) }
    function test_shr_19() { check(shr(2, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 9318714357181958935814889168420067934544147667529843450085708918447883222474) }
    function test_shr_20() { check(shr(2, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 15675739325768645020334369191971976881970487999945808684242755185235311577818) }
    function test_shr_21() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_shr_22() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_shr_23() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_shr_24() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shr_25() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shr_26() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 0) }
    function test_shr_27() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639935, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 0) }
    function test_shr_28() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_shr_29() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_shr_30() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_shr_31() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shr_32() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shr_33() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 0) }
    function test_shr_34() { check(shr(115792089237316195423570985008687907853269984665640564039457584007913129639934, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 0) }
    function test_shr_35() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 0), 0) }
    function test_shr_36() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 1), 0) }
    function test_shr_37() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 2), 0) }
    function test_shr_38() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shr_39() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shr_40() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 0) }
    function test_shr_41() { check(shr(37274857428727835743259556673680271738176590670119373800342835673791532889898, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 0) }
    function test_shr_42() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 0), 0) }
    function test_shr_43() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 1), 0) }
    function test_shr_44() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 2), 0) }
    function test_shr_45() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 0) }
    function test_shr_46() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 0) }
    function test_shr_47() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 37274857428727835743259556673680271738176590670119373800342835673791532889898), 0) }
    function test_shr_48() { check(shr(62702957303074580081337476767887907527881951999783234736971020740941246311273, 62702957303074580081337476767887907527881951999783234736971020740941246311273), 0) }

    function test_sar_0() { check(sar(0, 0), 0) }
    function test_sar_1() { check(sar(0, 1), 1) }
    function test_sar_2() { check(sar(0, 2), 2) }
    function test_sar_3() { check(sar(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_4() { check(sar(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_sar_5() { check(sar(0, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 82661433933280756441503497801869500397196377459062817609058635274434912526612) }
    function test_sar_6() { check(sar(0, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 14420977034312971726267164976326299024771581485143405760981081574949684199148) }
    function test_sar_7() { check(sar(1, 0), 0) }
    function test_sar_8() { check(sar(1, 1), 0) }
    function test_sar_9() { check(sar(1, 2), 1) }
    function test_sar_10() { check(sar(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_11() { check(sar(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_12() { check(sar(1, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 99226761585298475932537241405278704125233181062351690824258109641174021083274) }
    function test_sar_13() { check(sar(1, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 7210488517156485863133582488163149512385790742571702880490540787474842099574) }
    function test_sar_14() { check(sar(2, 0), 0) }
    function test_sar_15() { check(sar(2, 1), 0) }
    function test_sar_16() { check(sar(2, 2), 0) }
    function test_sar_17() { check(sar(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_18() { check(sar(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_19() { check(sar(2, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 107509425411307335678054113206983305989251582863996127431857846824543575361605) }
    function test_sar_20() { check(sar(2, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 3605244258578242931566791244081574756192895371285851440245270393737421049787) }
    function test_sar_21() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_sar_22() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 0) }
    function test_sar_23() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 0) }
    function test_sar_24() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_25() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_26() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_27() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639935, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 0) }
    function test_sar_28() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_sar_29() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 0) }
    function test_sar_30() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 0) }
    function test_sar_31() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_32() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_33() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_34() { check(sar(115792089237316195423570985008687907853269984665640564039457584007913129639934, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 0) }
    function test_sar_35() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 0), 0) }
    function test_sar_36() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 1), 0) }
    function test_sar_37() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 2), 0) }
    function test_sar_38() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_39() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_40() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_41() { check(sar(82661433933280756441503497801869500397196377459062817609058635274434912526612, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 0) }
    function test_sar_42() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 0), 0) }
    function test_sar_43() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 1), 0) }
    function test_sar_44() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 2), 0) }
    function test_sar_45() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_46() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_47() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 82661433933280756441503497801869500397196377459062817609058635274434912526612), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_sar_48() { check(sar(14420977034312971726267164976326299024771581485143405760981081574949684199148, 14420977034312971726267164976326299024771581485143405760981081574949684199148), 0) }

    function test_addmod_0() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 0) }
    function test_addmod_1() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 44064711991074734063141925668398245340558338981554495636670162568746986641924) }
    function test_addmod_2() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 5964384977369579789063133181789369635605431436912708810595518031967892371654) }
    function test_addmod_3() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 0), 0) }
    function test_addmod_4() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 44451158447482934193996014548064287383821425448259097478837643329632131616606) }
    function test_addmod_5() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 44257935219278834128568970108231266362189882214906796557753902949189559129265) }
    function test_addmod_6() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 4569900347129234874510872106258537737519845194360682068488508714197205522411) }
    function test_addmod_7() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 0), 0) }
    function test_addmod_8() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_9() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42670227360834389148589664592867413442472752739002468894563153250976299792681) }
    function test_addmod_10() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 2982192488684789894531566590894684817802715718456354405297759015983946185827) }
    function test_addmod_11() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 0), 0) }
    function test_addmod_12() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 0, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 0) }
    function test_addmod_13() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 0, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 44257935219278834128568970108231266362189882214906796557753902949189559129265) }
    function test_addmod_14() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 0, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 2982192488684789894531566590894684817802715718456354405297759015983946185827) }
    function test_addmod_15() { check(addmod(88709093666761768322564984656295553746011307663165894036591546278821690745871, 0, 0), 0) }
    function test_addmod_16() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 44451158447482934193996014548064287383821425448259097478837643329632131616606) }
    function test_addmod_17() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 44257935219278834128568970108231266362189882214906796557753902949189559129265) }
    function test_addmod_18() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 4569900347129234874510872106258537737519845194360682068488508714197205522411) }
    function test_addmod_19() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 0), 0) }
    function test_addmod_20() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 193223228204100065427044439833021021631543233352300921083740380442572487341) }
    function test_addmod_21() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 0) }
    function test_addmod_22() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 3175415716888889959958611030727705839434258951808655326381499396426518673168) }
    function test_addmod_23() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 0), 0) }
    function test_addmod_24() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 87314609036521423408012723580764721847925721420613867294484536961051003896628) }
    function test_addmod_25() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_26() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 1587707858444444979979305515363852919717129475904327663190749698213259336584) }
    function test_addmod_27() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 0), 0) }
    function test_addmod_28() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 0, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 44451158447482934193996014548064287383821425448259097478837643329632131616606) }
    function test_addmod_29() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 0, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 0) }
    function test_addmod_30() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 0, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 1587707858444444979979305515363852919717129475904327663190749698213259336584) }
    function test_addmod_31() { check(addmod(44451158447482934193996014548064287383821425448259097478837643329632131616606, 0, 0), 0) }
    function test_addmod_32() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_33() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42670227360834389148589664592867413442472752739002468894563153250976299792681) }
    function test_addmod_34() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 2982192488684789894531566590894684817802715718456354405297759015983946185827) }
    function test_addmod_35() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 0), 0) }
    function test_addmod_36() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 87314609036521423408012723580764721847925721420613867294484536961051003896628) }
    function test_addmod_37() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_38() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 1587707858444444979979305515363852919717129475904327663190749698213259336584) }
    function test_addmod_39() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 0), 0) }
    function test_addmod_40() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 85726901178076978428033418065400868928208591944709539631293787262837744560044) }
    function test_addmod_41() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 41275742730594044234037403517336581544387166496450442152456143933205612943438) }
    function test_addmod_42() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 0) }
    function test_addmod_43() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 0), 0) }
    function test_addmod_44() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 0, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_45() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 0, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_46() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 0, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 0) }
    function test_addmod_47() { check(addmod(42863450589038489214016709032700434464104295972354769815646893631418872280022, 0, 0), 0) }
    function test_addmod_48() { check(addmod(0, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 0) }
    function test_addmod_49() { check(addmod(0, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 44257935219278834128568970108231266362189882214906796557753902949189559129265) }
    function test_addmod_50() { check(addmod(0, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 2982192488684789894531566590894684817802715718456354405297759015983946185827) }
    function test_addmod_51() { check(addmod(0, 88709093666761768322564984656295553746011307663165894036591546278821690745871, 0), 0) }
    function test_addmod_52() { check(addmod(0, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 44451158447482934193996014548064287383821425448259097478837643329632131616606) }
    function test_addmod_53() { check(addmod(0, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 0) }
    function test_addmod_54() { check(addmod(0, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 1587707858444444979979305515363852919717129475904327663190749698213259336584) }
    function test_addmod_55() { check(addmod(0, 44451158447482934193996014548064287383821425448259097478837643329632131616606, 0), 0) }
    function test_addmod_56() { check(addmod(0, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_57() { check(addmod(0, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 42863450589038489214016709032700434464104295972354769815646893631418872280022) }
    function test_addmod_58() { check(addmod(0, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 0) }
    function test_addmod_59() { check(addmod(0, 42863450589038489214016709032700434464104295972354769815646893631418872280022, 0), 0) }
    function test_addmod_60() { check(addmod(0, 0, 88709093666761768322564984656295553746011307663165894036591546278821690745871), 0) }
    function test_addmod_61() { check(addmod(0, 0, 44451158447482934193996014548064287383821425448259097478837643329632131616606), 0) }
    function test_addmod_62() { check(addmod(0, 0, 42863450589038489214016709032700434464104295972354769815646893631418872280022), 0) }
    function test_addmod_63() { check(addmod(0, 0, 0), 0) }

    function test_mulmod_0() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_1() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 23176262005655255446619359110129527035459439612185431273098370546916359809784) }
    function test_mulmod_2() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 3064413551412437379643402604175968711223346206174540482441154607878557113688) }
    function test_mulmod_3() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 0), 0) }
    function test_mulmod_4() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_5() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_6() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 26273319191600029136698077734670861513821018779504641911485538517341065862878) }
    function test_mulmod_7() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 0), 0) }
    function test_mulmod_8() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_9() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 14157633310473631021856837273480583446391162130909985860868842352910678494940) }
    function test_mulmod_10() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_11() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 0), 0) }
    function test_mulmod_12() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 0, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_13() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 0, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_14() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 0, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_15() { check(mulmod(16276669522384486338889180648183030066755182847217443080768578804831749401628, 0, 0), 0) }
    function test_mulmod_16() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_17() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_18() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 26273319191600029136698077734670861513821018779504641911485538517341065862878) }
    function test_mulmod_19() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 0), 0) }
    function test_mulmod_20() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 10264553014886949099456832205662211287802170691660629981149545306256743595357) }
    function test_mulmod_21() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_22() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 40376042472371261823328543819007916619907748689918933898580231748226231028508) }
    function test_mulmod_23() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 0), 0) }
    function test_mulmod_24() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 121166042667900601775491320570584362863069218419613427774684657728630002551) }
    function test_mulmod_25() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_26() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_27() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 0), 0) }
    function test_mulmod_28() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 0, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_29() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 0, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_30() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 0, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_31() { check(mulmod(61255369845337909531357383249661018806600642830892900657424556972616011860017, 0, 0), 0) }
    function test_mulmod_32() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_33() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 14157633310473631021856837273480583446391162130909985860868842352910678494940) }
    function test_mulmod_34() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_35() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 0), 0) }
    function test_mulmod_36() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 121166042667900601775491320570584362863069218419613427774684657728630002551) }
    function test_mulmod_37() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_38() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_39() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 0), 0) }
    function test_mulmod_40() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 11598696862827562854335940060986693325168146814706863022727054740069022270965) }
    function test_mulmod_41() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 59313540545305335696306027808474459684036927815722086527493987744136766311788) }
    function test_mulmod_42() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_43() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 0), 0) }
    function test_mulmod_44() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 0, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_45() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 0, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_46() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 0, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_47() { check(mulmod(67592269495322012340487158052845183801991789236173000628299730722890671725711, 0, 0), 0) }
    function test_mulmod_48() { check(mulmod(0, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_49() { check(mulmod(0, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_50() { check(mulmod(0, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_51() { check(mulmod(0, 16276669522384486338889180648183030066755182847217443080768578804831749401628, 0), 0) }
    function test_mulmod_52() { check(mulmod(0, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_53() { check(mulmod(0, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_54() { check(mulmod(0, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_55() { check(mulmod(0, 61255369845337909531357383249661018806600642830892900657424556972616011860017, 0), 0) }
    function test_mulmod_56() { check(mulmod(0, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_57() { check(mulmod(0, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_58() { check(mulmod(0, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_59() { check(mulmod(0, 67592269495322012340487158052845183801991789236173000628299730722890671725711, 0), 0) }
    function test_mulmod_60() { check(mulmod(0, 0, 16276669522384486338889180648183030066755182847217443080768578804831749401628), 0) }
    function test_mulmod_61() { check(mulmod(0, 0, 61255369845337909531357383249661018806600642830892900657424556972616011860017), 0) }
    function test_mulmod_62() { check(mulmod(0, 0, 67592269495322012340487158052845183801991789236173000628299730722890671725711), 0) }
    function test_mulmod_63() { check(mulmod(0, 0, 0), 0) }

    function test_signextend_0() { check(signextend(0, 0), 0) }
    function test_signextend_1() { check(signextend(0, 1), 1) }
    function test_signextend_2() { check(signextend(0, 2), 2) }
    function test_signextend_3() { check(signextend(0, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_4() { check(signextend(0, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_5() { check(signextend(0, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 115792089237316195423570985008687907853269984665640564039457584007913129639892) }
    function test_signextend_6() { check(signextend(0, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 115792089237316195423570985008687907853269984665640564039457584007913129639817) }
    function test_signextend_7() { check(signextend(1, 0), 0) }
    function test_signextend_8() { check(signextend(1, 1), 1) }
    function test_signextend_9() { check(signextend(1, 2), 2) }
    function test_signextend_10() { check(signextend(1, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_11() { check(signextend(1, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_12() { check(signextend(1, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 27092) }
    function test_signextend_13() { check(signextend(1, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 27273) }
    function test_signextend_14() { check(signextend(2, 0), 0) }
    function test_signextend_15() { check(signextend(2, 1), 1) }
    function test_signextend_16() { check(signextend(2, 2), 2) }
    function test_signextend_17() { check(signextend(2, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_18() { check(signextend(2, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_19() { check(signextend(2, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 2386388) }
    function test_signextend_20() { check(signextend(2, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 1272457) }
    function test_signextend_21() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 0), 0) }
    function test_signextend_22() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 1), 1) }
    function test_signextend_23() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 2), 2) }
    function test_signextend_24() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_25() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_26() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 45226673911494330638004017861787702005823510899832444576649689288606038125012) }
    function test_signextend_27() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639935, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 104679649160658165931730490444266492838683600858729223011136025312331610417801) }
    function test_signextend_28() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 0), 0) }
    function test_signextend_29() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 1), 1) }
    function test_signextend_30() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 2), 2) }
    function test_signextend_31() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_32() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_33() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 45226673911494330638004017861787702005823510899832444576649689288606038125012) }
    function test_signextend_34() { check(signextend(115792089237316195423570985008687907853269984665640564039457584007913129639934, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 104679649160658165931730490444266492838683600858729223011136025312331610417801) }
    function test_signextend_35() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 0), 0) }
    function test_signextend_36() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 1), 1) }
    function test_signextend_37() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 2), 2) }
    function test_signextend_38() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_39() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_40() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 45226673911494330638004017861787702005823510899832444576649689288606038125012) }
    function test_signextend_41() { check(signextend(45226673911494330638004017861787702005823510899832444576649689288606038125012, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 104679649160658165931730490444266492838683600858729223011136025312331610417801) }
    function test_signextend_42() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 0), 0) }
    function test_signextend_43() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 1), 1) }
    function test_signextend_44() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 2), 2) }
    function test_signextend_45() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 115792089237316195423570985008687907853269984665640564039457584007913129639935), 115792089237316195423570985008687907853269984665640564039457584007913129639935) }
    function test_signextend_46() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 115792089237316195423570985008687907853269984665640564039457584007913129639934), 115792089237316195423570985008687907853269984665640564039457584007913129639934) }
    function test_signextend_47() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 45226673911494330638004017861787702005823510899832444576649689288606038125012), 45226673911494330638004017861787702005823510899832444576649689288606038125012) }
    function test_signextend_48() { check(signextend(104679649160658165931730490444266492838683600858729223011136025312331610417801, 104679649160658165931730490444266492838683600858729223011136025312331610417801), 104679649160658165931730490444266492838683600858729223011136025312331610417801) }

}
// ----
// step: constantFunctionEvaluator
//
// {
//     function check(a, b)
//     {
//         if iszero(eq(a, b)) { revert(0, 0) }
//     }
//     function test_add_0()
//     { }
//     function test_add_1()
//     { }
//     function test_add_2()
//     { }
//     function test_add_3()
//     { }
//     function test_add_4()
//     { }
//     function test_add_5()
//     { }
//     function test_add_6()
//     { }
//     function test_add_7()
//     { }
//     function test_add_8()
//     { }
//     function test_add_9()
//     { }
//     function test_add_10()
//     { }
//     function test_add_11()
//     { }
//     function test_add_12()
//     { }
//     function test_add_13()
//     { }
//     function test_add_14()
//     { }
//     function test_add_15()
//     { }
//     function test_add_16()
//     { }
//     function test_add_17()
//     { }
//     function test_add_18()
//     { }
//     function test_add_19()
//     { }
//     function test_add_20()
//     { }
//     function test_add_21()
//     { }
//     function test_add_22()
//     { }
//     function test_add_23()
//     { }
//     function test_add_24()
//     { }
//     function test_add_25()
//     { }
//     function test_add_26()
//     { }
//     function test_add_27()
//     { }
//     function test_add_28()
//     { }
//     function test_add_29()
//     { }
//     function test_add_30()
//     { }
//     function test_add_31()
//     { }
//     function test_add_32()
//     { }
//     function test_add_33()
//     { }
//     function test_add_34()
//     { }
//     function test_add_35()
//     { }
//     function test_add_36()
//     { }
//     function test_add_37()
//     { }
//     function test_add_38()
//     { }
//     function test_add_39()
//     { }
//     function test_add_40()
//     { }
//     function test_add_41()
//     { }
//     function test_add_42()
//     { }
//     function test_add_43()
//     { }
//     function test_add_44()
//     { }
//     function test_add_45()
//     { }
//     function test_add_46()
//     { }
//     function test_add_47()
//     { }
//     function test_add_48()
//     { }
//     function test_mul_0()
//     { }
//     function test_mul_1()
//     { }
//     function test_mul_2()
//     { }
//     function test_mul_3()
//     { }
//     function test_mul_4()
//     { }
//     function test_mul_5()
//     { }
//     function test_mul_6()
//     { }
//     function test_mul_7()
//     { }
//     function test_mul_8()
//     { }
//     function test_mul_9()
//     { }
//     function test_mul_10()
//     { }
//     function test_mul_11()
//     { }
//     function test_mul_12()
//     { }
//     function test_mul_13()
//     { }
//     function test_mul_14()
//     { }
//     function test_mul_15()
//     { }
//     function test_mul_16()
//     { }
//     function test_mul_17()
//     { }
//     function test_mul_18()
//     { }
//     function test_mul_19()
//     { }
//     function test_mul_20()
//     { }
//     function test_mul_21()
//     { }
//     function test_mul_22()
//     { }
//     function test_mul_23()
//     { }
//     function test_mul_24()
//     { }
//     function test_mul_25()
//     { }
//     function test_mul_26()
//     { }
//     function test_mul_27()
//     { }
//     function test_mul_28()
//     { }
//     function test_mul_29()
//     { }
//     function test_mul_30()
//     { }
//     function test_mul_31()
//     { }
//     function test_mul_32()
//     { }
//     function test_mul_33()
//     { }
//     function test_mul_34()
//     { }
//     function test_mul_35()
//     { }
//     function test_mul_36()
//     { }
//     function test_mul_37()
//     { }
//     function test_mul_38()
//     { }
//     function test_mul_39()
//     { }
//     function test_mul_40()
//     { }
//     function test_mul_41()
//     { }
//     function test_mul_42()
//     { }
//     function test_mul_43()
//     { }
//     function test_mul_44()
//     { }
//     function test_mul_45()
//     { }
//     function test_mul_46()
//     { }
//     function test_mul_47()
//     { }
//     function test_mul_48()
//     { }
//     function test_sub_0()
//     { }
//     function test_sub_1()
//     { }
//     function test_sub_2()
//     { }
//     function test_sub_3()
//     { }
//     function test_sub_4()
//     { }
//     function test_sub_5()
//     { }
//     function test_sub_6()
//     { }
//     function test_sub_7()
//     { }
//     function test_sub_8()
//     { }
//     function test_sub_9()
//     { }
//     function test_sub_10()
//     { }
//     function test_sub_11()
//     { }
//     function test_sub_12()
//     { }
//     function test_sub_13()
//     { }
//     function test_sub_14()
//     { }
//     function test_sub_15()
//     { }
//     function test_sub_16()
//     { }
//     function test_sub_17()
//     { }
//     function test_sub_18()
//     { }
//     function test_sub_19()
//     { }
//     function test_sub_20()
//     { }
//     function test_sub_21()
//     { }
//     function test_sub_22()
//     { }
//     function test_sub_23()
//     { }
//     function test_sub_24()
//     { }
//     function test_sub_25()
//     { }
//     function test_sub_26()
//     { }
//     function test_sub_27()
//     { }
//     function test_sub_28()
//     { }
//     function test_sub_29()
//     { }
//     function test_sub_30()
//     { }
//     function test_sub_31()
//     { }
//     function test_sub_32()
//     { }
//     function test_sub_33()
//     { }
//     function test_sub_34()
//     { }
//     function test_sub_35()
//     { }
//     function test_sub_36()
//     { }
//     function test_sub_37()
//     { }
//     function test_sub_38()
//     { }
//     function test_sub_39()
//     { }
//     function test_sub_40()
//     { }
//     function test_sub_41()
//     { }
//     function test_sub_42()
//     { }
//     function test_sub_43()
//     { }
//     function test_sub_44()
//     { }
//     function test_sub_45()
//     { }
//     function test_sub_46()
//     { }
//     function test_sub_47()
//     { }
//     function test_sub_48()
//     { }
//     function test_div_0()
//     { }
//     function test_div_1()
//     { }
//     function test_div_2()
//     { }
//     function test_div_3()
//     { }
//     function test_div_4()
//     { }
//     function test_div_5()
//     { }
//     function test_div_6()
//     { }
//     function test_div_7()
//     { }
//     function test_div_8()
//     { }
//     function test_div_9()
//     { }
//     function test_div_10()
//     { }
//     function test_div_11()
//     { }
//     function test_div_12()
//     { }
//     function test_div_13()
//     { }
//     function test_div_14()
//     { }
//     function test_div_15()
//     { }
//     function test_div_16()
//     { }
//     function test_div_17()
//     { }
//     function test_div_18()
//     { }
//     function test_div_19()
//     { }
//     function test_div_20()
//     { }
//     function test_div_21()
//     { }
//     function test_div_22()
//     { }
//     function test_div_23()
//     { }
//     function test_div_24()
//     { }
//     function test_div_25()
//     { }
//     function test_div_26()
//     { }
//     function test_div_27()
//     { }
//     function test_div_28()
//     { }
//     function test_div_29()
//     { }
//     function test_div_30()
//     { }
//     function test_div_31()
//     { }
//     function test_div_32()
//     { }
//     function test_div_33()
//     { }
//     function test_div_34()
//     { }
//     function test_div_35()
//     { }
//     function test_div_36()
//     { }
//     function test_div_37()
//     { }
//     function test_div_38()
//     { }
//     function test_div_39()
//     { }
//     function test_div_40()
//     { }
//     function test_div_41()
//     { }
//     function test_div_42()
//     { }
//     function test_div_43()
//     { }
//     function test_div_44()
//     { }
//     function test_div_45()
//     { }
//     function test_div_46()
//     { }
//     function test_div_47()
//     { }
//     function test_div_48()
//     { }
//     function test_sdiv_0()
//     { }
//     function test_sdiv_1()
//     { }
//     function test_sdiv_2()
//     { }
//     function test_sdiv_3()
//     { }
//     function test_sdiv_4()
//     { }
//     function test_sdiv_5()
//     { }
//     function test_sdiv_6()
//     { }
//     function test_sdiv_7()
//     { }
//     function test_sdiv_8()
//     { }
//     function test_sdiv_9()
//     { }
//     function test_sdiv_10()
//     { }
//     function test_sdiv_11()
//     { }
//     function test_sdiv_12()
//     { }
//     function test_sdiv_13()
//     { }
//     function test_sdiv_14()
//     { }
//     function test_sdiv_15()
//     { }
//     function test_sdiv_16()
//     { }
//     function test_sdiv_17()
//     { }
//     function test_sdiv_18()
//     { }
//     function test_sdiv_19()
//     { }
//     function test_sdiv_20()
//     { }
//     function test_sdiv_21()
//     { }
//     function test_sdiv_22()
//     { }
//     function test_sdiv_23()
//     { }
//     function test_sdiv_24()
//     { }
//     function test_sdiv_25()
//     { }
//     function test_sdiv_26()
//     { }
//     function test_sdiv_27()
//     { }
//     function test_sdiv_28()
//     { }
//     function test_sdiv_29()
//     { }
//     function test_sdiv_30()
//     { }
//     function test_sdiv_31()
//     { }
//     function test_sdiv_32()
//     { }
//     function test_sdiv_33()
//     { }
//     function test_sdiv_34()
//     { }
//     function test_sdiv_35()
//     { }
//     function test_sdiv_36()
//     { }
//     function test_sdiv_37()
//     { }
//     function test_sdiv_38()
//     { }
//     function test_sdiv_39()
//     { }
//     function test_sdiv_40()
//     { }
//     function test_sdiv_41()
//     { }
//     function test_sdiv_42()
//     { }
//     function test_sdiv_43()
//     { }
//     function test_sdiv_44()
//     { }
//     function test_sdiv_45()
//     { }
//     function test_sdiv_46()
//     { }
//     function test_sdiv_47()
//     { }
//     function test_sdiv_48()
//     { }
//     function test_mod_0()
//     { }
//     function test_mod_1()
//     { }
//     function test_mod_2()
//     { }
//     function test_mod_3()
//     { }
//     function test_mod_4()
//     { }
//     function test_mod_5()
//     { }
//     function test_mod_6()
//     { }
//     function test_mod_7()
//     { }
//     function test_mod_8()
//     { }
//     function test_mod_9()
//     { }
//     function test_mod_10()
//     { }
//     function test_mod_11()
//     { }
//     function test_mod_12()
//     { }
//     function test_mod_13()
//     { }
//     function test_mod_14()
//     { }
//     function test_mod_15()
//     { }
//     function test_mod_16()
//     { }
//     function test_mod_17()
//     { }
//     function test_mod_18()
//     { }
//     function test_mod_19()
//     { }
//     function test_mod_20()
//     { }
//     function test_mod_21()
//     { }
//     function test_mod_22()
//     { }
//     function test_mod_23()
//     { }
//     function test_mod_24()
//     { }
//     function test_mod_25()
//     { }
//     function test_mod_26()
//     { }
//     function test_mod_27()
//     { }
//     function test_mod_28()
//     { }
//     function test_mod_29()
//     { }
//     function test_mod_30()
//     { }
//     function test_mod_31()
//     { }
//     function test_mod_32()
//     { }
//     function test_mod_33()
//     { }
//     function test_mod_34()
//     { }
//     function test_mod_35()
//     { }
//     function test_mod_36()
//     { }
//     function test_mod_37()
//     { }
//     function test_mod_38()
//     { }
//     function test_mod_39()
//     { }
//     function test_mod_40()
//     { }
//     function test_mod_41()
//     { }
//     function test_mod_42()
//     { }
//     function test_mod_43()
//     { }
//     function test_mod_44()
//     { }
//     function test_mod_45()
//     { }
//     function test_mod_46()
//     { }
//     function test_mod_47()
//     { }
//     function test_mod_48()
//     { }
//     function test_smod_0()
//     { }
//     function test_smod_1()
//     { }
//     function test_smod_2()
//     { }
//     function test_smod_3()
//     { }
//     function test_smod_4()
//     { }
//     function test_smod_5()
//     { }
//     function test_smod_6()
//     { }
//     function test_smod_7()
//     { }
//     function test_smod_8()
//     { }
//     function test_smod_9()
//     { }
//     function test_smod_10()
//     { }
//     function test_smod_11()
//     { }
//     function test_smod_12()
//     { }
//     function test_smod_13()
//     { }
//     function test_smod_14()
//     { }
//     function test_smod_15()
//     { }
//     function test_smod_16()
//     { }
//     function test_smod_17()
//     { }
//     function test_smod_18()
//     { }
//     function test_smod_19()
//     { }
//     function test_smod_20()
//     { }
//     function test_smod_21()
//     { }
//     function test_smod_22()
//     { }
//     function test_smod_23()
//     { }
//     function test_smod_24()
//     { }
//     function test_smod_25()
//     { }
//     function test_smod_26()
//     { }
//     function test_smod_27()
//     { }
//     function test_smod_28()
//     { }
//     function test_smod_29()
//     { }
//     function test_smod_30()
//     { }
//     function test_smod_31()
//     { }
//     function test_smod_32()
//     { }
//     function test_smod_33()
//     { }
//     function test_smod_34()
//     { }
//     function test_smod_35()
//     { }
//     function test_smod_36()
//     { }
//     function test_smod_37()
//     { }
//     function test_smod_38()
//     { }
//     function test_smod_39()
//     { }
//     function test_smod_40()
//     { }
//     function test_smod_41()
//     { }
//     function test_smod_42()
//     { }
//     function test_smod_43()
//     { }
//     function test_smod_44()
//     { }
//     function test_smod_45()
//     { }
//     function test_smod_46()
//     { }
//     function test_smod_47()
//     { }
//     function test_smod_48()
//     { }
//     function test_exp_0()
//     { }
//     function test_exp_1()
//     { }
//     function test_exp_2()
//     { }
//     function test_exp_3()
//     { }
//     function test_exp_4()
//     { }
//     function test_exp_5()
//     { }
//     function test_exp_6()
//     { }
//     function test_exp_7()
//     { }
//     function test_exp_8()
//     { }
//     function test_exp_9()
//     { }
//     function test_exp_10()
//     { }
//     function test_exp_11()
//     { }
//     function test_exp_12()
//     { }
//     function test_exp_13()
//     { }
//     function test_exp_14()
//     { }
//     function test_exp_15()
//     { }
//     function test_exp_16()
//     { }
//     function test_exp_17()
//     { }
//     function test_exp_18()
//     { }
//     function test_exp_19()
//     { }
//     function test_exp_20()
//     { }
//     function test_exp_21()
//     { }
//     function test_exp_22()
//     { }
//     function test_exp_23()
//     { }
//     function test_exp_24()
//     { }
//     function test_exp_25()
//     { }
//     function test_exp_26()
//     { }
//     function test_exp_27()
//     { }
//     function test_exp_28()
//     { }
//     function test_exp_29()
//     { }
//     function test_exp_30()
//     { }
//     function test_exp_31()
//     { }
//     function test_exp_32()
//     { }
//     function test_exp_33()
//     { }
//     function test_exp_34()
//     { }
//     function test_exp_35()
//     { }
//     function test_exp_36()
//     { }
//     function test_exp_37()
//     { }
//     function test_exp_38()
//     { }
//     function test_exp_39()
//     { }
//     function test_exp_40()
//     { }
//     function test_exp_41()
//     { }
//     function test_exp_42()
//     { }
//     function test_exp_43()
//     { }
//     function test_exp_44()
//     { }
//     function test_exp_45()
//     { }
//     function test_exp_46()
//     { }
//     function test_exp_47()
//     { }
//     function test_exp_48()
//     { }
//     function test_not_0()
//     { }
//     function test_not_1()
//     { }
//     function test_not_2()
//     { }
//     function test_not_3()
//     { }
//     function test_not_4()
//     { }
//     function test_not_5()
//     { }
//     function test_not_6()
//     { }
//     function test_lt_0()
//     { }
//     function test_lt_1()
//     { }
//     function test_lt_2()
//     { }
//     function test_lt_3()
//     { }
//     function test_lt_4()
//     { }
//     function test_lt_5()
//     { }
//     function test_lt_6()
//     { }
//     function test_lt_7()
//     { }
//     function test_lt_8()
//     { }
//     function test_lt_9()
//     { }
//     function test_lt_10()
//     { }
//     function test_lt_11()
//     { }
//     function test_lt_12()
//     { }
//     function test_lt_13()
//     { }
//     function test_lt_14()
//     { }
//     function test_lt_15()
//     { }
//     function test_lt_16()
//     { }
//     function test_lt_17()
//     { }
//     function test_lt_18()
//     { }
//     function test_lt_19()
//     { }
//     function test_lt_20()
//     { }
//     function test_lt_21()
//     { }
//     function test_lt_22()
//     { }
//     function test_lt_23()
//     { }
//     function test_lt_24()
//     { }
//     function test_lt_25()
//     { }
//     function test_lt_26()
//     { }
//     function test_lt_27()
//     { }
//     function test_lt_28()
//     { }
//     function test_lt_29()
//     { }
//     function test_lt_30()
//     { }
//     function test_lt_31()
//     { }
//     function test_lt_32()
//     { }
//     function test_lt_33()
//     { }
//     function test_lt_34()
//     { }
//     function test_lt_35()
//     { }
//     function test_lt_36()
//     { }
//     function test_lt_37()
//     { }
//     function test_lt_38()
//     { }
//     function test_lt_39()
//     { }
//     function test_lt_40()
//     { }
//     function test_lt_41()
//     { }
//     function test_lt_42()
//     { }
//     function test_lt_43()
//     { }
//     function test_lt_44()
//     { }
//     function test_lt_45()
//     { }
//     function test_lt_46()
//     { }
//     function test_lt_47()
//     { }
//     function test_lt_48()
//     { }
//     function test_gt_0()
//     { }
//     function test_gt_1()
//     { }
//     function test_gt_2()
//     { }
//     function test_gt_3()
//     { }
//     function test_gt_4()
//     { }
//     function test_gt_5()
//     { }
//     function test_gt_6()
//     { }
//     function test_gt_7()
//     { }
//     function test_gt_8()
//     { }
//     function test_gt_9()
//     { }
//     function test_gt_10()
//     { }
//     function test_gt_11()
//     { }
//     function test_gt_12()
//     { }
//     function test_gt_13()
//     { }
//     function test_gt_14()
//     { }
//     function test_gt_15()
//     { }
//     function test_gt_16()
//     { }
//     function test_gt_17()
//     { }
//     function test_gt_18()
//     { }
//     function test_gt_19()
//     { }
//     function test_gt_20()
//     { }
//     function test_gt_21()
//     { }
//     function test_gt_22()
//     { }
//     function test_gt_23()
//     { }
//     function test_gt_24()
//     { }
//     function test_gt_25()
//     { }
//     function test_gt_26()
//     { }
//     function test_gt_27()
//     { }
//     function test_gt_28()
//     { }
//     function test_gt_29()
//     { }
//     function test_gt_30()
//     { }
//     function test_gt_31()
//     { }
//     function test_gt_32()
//     { }
//     function test_gt_33()
//     { }
//     function test_gt_34()
//     { }
//     function test_gt_35()
//     { }
//     function test_gt_36()
//     { }
//     function test_gt_37()
//     { }
//     function test_gt_38()
//     { }
//     function test_gt_39()
//     { }
//     function test_gt_40()
//     { }
//     function test_gt_41()
//     { }
//     function test_gt_42()
//     { }
//     function test_gt_43()
//     { }
//     function test_gt_44()
//     { }
//     function test_gt_45()
//     { }
//     function test_gt_46()
//     { }
//     function test_gt_47()
//     { }
//     function test_gt_48()
//     { }
//     function test_slt_0()
//     { }
//     function test_slt_1()
//     { }
//     function test_slt_2()
//     { }
//     function test_slt_3()
//     { }
//     function test_slt_4()
//     { }
//     function test_slt_5()
//     { }
//     function test_slt_6()
//     { }
//     function test_slt_7()
//     { }
//     function test_slt_8()
//     { }
//     function test_slt_9()
//     { }
//     function test_slt_10()
//     { }
//     function test_slt_11()
//     { }
//     function test_slt_12()
//     { }
//     function test_slt_13()
//     { }
//     function test_slt_14()
//     { }
//     function test_slt_15()
//     { }
//     function test_slt_16()
//     { }
//     function test_slt_17()
//     { }
//     function test_slt_18()
//     { }
//     function test_slt_19()
//     { }
//     function test_slt_20()
//     { }
//     function test_slt_21()
//     { }
//     function test_slt_22()
//     { }
//     function test_slt_23()
//     { }
//     function test_slt_24()
//     { }
//     function test_slt_25()
//     { }
//     function test_slt_26()
//     { }
//     function test_slt_27()
//     { }
//     function test_slt_28()
//     { }
//     function test_slt_29()
//     { }
//     function test_slt_30()
//     { }
//     function test_slt_31()
//     { }
//     function test_slt_32()
//     { }
//     function test_slt_33()
//     { }
//     function test_slt_34()
//     { }
//     function test_slt_35()
//     { }
//     function test_slt_36()
//     { }
//     function test_slt_37()
//     { }
//     function test_slt_38()
//     { }
//     function test_slt_39()
//     { }
//     function test_slt_40()
//     { }
//     function test_slt_41()
//     { }
//     function test_slt_42()
//     { }
//     function test_slt_43()
//     { }
//     function test_slt_44()
//     { }
//     function test_slt_45()
//     { }
//     function test_slt_46()
//     { }
//     function test_slt_47()
//     { }
//     function test_slt_48()
//     { }
//     function test_sgt_0()
//     { }
//     function test_sgt_1()
//     { }
//     function test_sgt_2()
//     { }
//     function test_sgt_3()
//     { }
//     function test_sgt_4()
//     { }
//     function test_sgt_5()
//     { }
//     function test_sgt_6()
//     { }
//     function test_sgt_7()
//     { }
//     function test_sgt_8()
//     { }
//     function test_sgt_9()
//     { }
//     function test_sgt_10()
//     { }
//     function test_sgt_11()
//     { }
//     function test_sgt_12()
//     { }
//     function test_sgt_13()
//     { }
//     function test_sgt_14()
//     { }
//     function test_sgt_15()
//     { }
//     function test_sgt_16()
//     { }
//     function test_sgt_17()
//     { }
//     function test_sgt_18()
//     { }
//     function test_sgt_19()
//     { }
//     function test_sgt_20()
//     { }
//     function test_sgt_21()
//     { }
//     function test_sgt_22()
//     { }
//     function test_sgt_23()
//     { }
//     function test_sgt_24()
//     { }
//     function test_sgt_25()
//     { }
//     function test_sgt_26()
//     { }
//     function test_sgt_27()
//     { }
//     function test_sgt_28()
//     { }
//     function test_sgt_29()
//     { }
//     function test_sgt_30()
//     { }
//     function test_sgt_31()
//     { }
//     function test_sgt_32()
//     { }
//     function test_sgt_33()
//     { }
//     function test_sgt_34()
//     { }
//     function test_sgt_35()
//     { }
//     function test_sgt_36()
//     { }
//     function test_sgt_37()
//     { }
//     function test_sgt_38()
//     { }
//     function test_sgt_39()
//     { }
//     function test_sgt_40()
//     { }
//     function test_sgt_41()
//     { }
//     function test_sgt_42()
//     { }
//     function test_sgt_43()
//     { }
//     function test_sgt_44()
//     { }
//     function test_sgt_45()
//     { }
//     function test_sgt_46()
//     { }
//     function test_sgt_47()
//     { }
//     function test_sgt_48()
//     { }
//     function test_eq_0()
//     { }
//     function test_eq_1()
//     { }
//     function test_eq_2()
//     { }
//     function test_eq_3()
//     { }
//     function test_eq_4()
//     { }
//     function test_eq_5()
//     { }
//     function test_eq_6()
//     { }
//     function test_eq_7()
//     { }
//     function test_eq_8()
//     { }
//     function test_eq_9()
//     { }
//     function test_eq_10()
//     { }
//     function test_eq_11()
//     { }
//     function test_eq_12()
//     { }
//     function test_eq_13()
//     { }
//     function test_eq_14()
//     { }
//     function test_eq_15()
//     { }
//     function test_eq_16()
//     { }
//     function test_eq_17()
//     { }
//     function test_eq_18()
//     { }
//     function test_eq_19()
//     { }
//     function test_eq_20()
//     { }
//     function test_eq_21()
//     { }
//     function test_eq_22()
//     { }
//     function test_eq_23()
//     { }
//     function test_eq_24()
//     { }
//     function test_eq_25()
//     { }
//     function test_eq_26()
//     { }
//     function test_eq_27()
//     { }
//     function test_eq_28()
//     { }
//     function test_eq_29()
//     { }
//     function test_eq_30()
//     { }
//     function test_eq_31()
//     { }
//     function test_eq_32()
//     { }
//     function test_eq_33()
//     { }
//     function test_eq_34()
//     { }
//     function test_eq_35()
//     { }
//     function test_eq_36()
//     { }
//     function test_eq_37()
//     { }
//     function test_eq_38()
//     { }
//     function test_eq_39()
//     { }
//     function test_eq_40()
//     { }
//     function test_eq_41()
//     { }
//     function test_eq_42()
//     { }
//     function test_eq_43()
//     { }
//     function test_eq_44()
//     { }
//     function test_eq_45()
//     { }
//     function test_eq_46()
//     { }
//     function test_eq_47()
//     { }
//     function test_eq_48()
//     { }
//     function test_iszero_0()
//     { }
//     function test_iszero_1()
//     { }
//     function test_iszero_2()
//     { }
//     function test_iszero_3()
//     { }
//     function test_iszero_4()
//     { }
//     function test_iszero_5()
//     { }
//     function test_iszero_6()
//     { }
//     function test_and_0()
//     { }
//     function test_and_1()
//     { }
//     function test_and_2()
//     { }
//     function test_and_3()
//     { }
//     function test_and_4()
//     { }
//     function test_and_5()
//     { }
//     function test_and_6()
//     { }
//     function test_and_7()
//     { }
//     function test_and_8()
//     { }
//     function test_and_9()
//     { }
//     function test_and_10()
//     { }
//     function test_and_11()
//     { }
//     function test_and_12()
//     { }
//     function test_and_13()
//     { }
//     function test_and_14()
//     { }
//     function test_and_15()
//     { }
//     function test_and_16()
//     { }
//     function test_and_17()
//     { }
//     function test_and_18()
//     { }
//     function test_and_19()
//     { }
//     function test_and_20()
//     { }
//     function test_and_21()
//     { }
//     function test_and_22()
//     { }
//     function test_and_23()
//     { }
//     function test_and_24()
//     { }
//     function test_and_25()
//     { }
//     function test_and_26()
//     { }
//     function test_and_27()
//     { }
//     function test_and_28()
//     { }
//     function test_and_29()
//     { }
//     function test_and_30()
//     { }
//     function test_and_31()
//     { }
//     function test_and_32()
//     { }
//     function test_and_33()
//     { }
//     function test_and_34()
//     { }
//     function test_and_35()
//     { }
//     function test_and_36()
//     { }
//     function test_and_37()
//     { }
//     function test_and_38()
//     { }
//     function test_and_39()
//     { }
//     function test_and_40()
//     { }
//     function test_and_41()
//     { }
//     function test_and_42()
//     { }
//     function test_and_43()
//     { }
//     function test_and_44()
//     { }
//     function test_and_45()
//     { }
//     function test_and_46()
//     { }
//     function test_and_47()
//     { }
//     function test_and_48()
//     { }
//     function test_or_0()
//     { }
//     function test_or_1()
//     { }
//     function test_or_2()
//     { }
//     function test_or_3()
//     { }
//     function test_or_4()
//     { }
//     function test_or_5()
//     { }
//     function test_or_6()
//     { }
//     function test_or_7()
//     { }
//     function test_or_8()
//     { }
//     function test_or_9()
//     { }
//     function test_or_10()
//     { }
//     function test_or_11()
//     { }
//     function test_or_12()
//     { }
//     function test_or_13()
//     { }
//     function test_or_14()
//     { }
//     function test_or_15()
//     { }
//     function test_or_16()
//     { }
//     function test_or_17()
//     { }
//     function test_or_18()
//     { }
//     function test_or_19()
//     { }
//     function test_or_20()
//     { }
//     function test_or_21()
//     { }
//     function test_or_22()
//     { }
//     function test_or_23()
//     { }
//     function test_or_24()
//     { }
//     function test_or_25()
//     { }
//     function test_or_26()
//     { }
//     function test_or_27()
//     { }
//     function test_or_28()
//     { }
//     function test_or_29()
//     { }
//     function test_or_30()
//     { }
//     function test_or_31()
//     { }
//     function test_or_32()
//     { }
//     function test_or_33()
//     { }
//     function test_or_34()
//     { }
//     function test_or_35()
//     { }
//     function test_or_36()
//     { }
//     function test_or_37()
//     { }
//     function test_or_38()
//     { }
//     function test_or_39()
//     { }
//     function test_or_40()
//     { }
//     function test_or_41()
//     { }
//     function test_or_42()
//     { }
//     function test_or_43()
//     { }
//     function test_or_44()
//     { }
//     function test_or_45()
//     { }
//     function test_or_46()
//     { }
//     function test_or_47()
//     { }
//     function test_or_48()
//     { }
//     function test_xor_0()
//     { }
//     function test_xor_1()
//     { }
//     function test_xor_2()
//     { }
//     function test_xor_3()
//     { }
//     function test_xor_4()
//     { }
//     function test_xor_5()
//     { }
//     function test_xor_6()
//     { }
//     function test_xor_7()
//     { }
//     function test_xor_8()
//     { }
//     function test_xor_9()
//     { }
//     function test_xor_10()
//     { }
//     function test_xor_11()
//     { }
//     function test_xor_12()
//     { }
//     function test_xor_13()
//     { }
//     function test_xor_14()
//     { }
//     function test_xor_15()
//     { }
//     function test_xor_16()
//     { }
//     function test_xor_17()
//     { }
//     function test_xor_18()
//     { }
//     function test_xor_19()
//     { }
//     function test_xor_20()
//     { }
//     function test_xor_21()
//     { }
//     function test_xor_22()
//     { }
//     function test_xor_23()
//     { }
//     function test_xor_24()
//     { }
//     function test_xor_25()
//     { }
//     function test_xor_26()
//     { }
//     function test_xor_27()
//     { }
//     function test_xor_28()
//     { }
//     function test_xor_29()
//     { }
//     function test_xor_30()
//     { }
//     function test_xor_31()
//     { }
//     function test_xor_32()
//     { }
//     function test_xor_33()
//     { }
//     function test_xor_34()
//     { }
//     function test_xor_35()
//     { }
//     function test_xor_36()
//     { }
//     function test_xor_37()
//     { }
//     function test_xor_38()
//     { }
//     function test_xor_39()
//     { }
//     function test_xor_40()
//     { }
//     function test_xor_41()
//     { }
//     function test_xor_42()
//     { }
//     function test_xor_43()
//     { }
//     function test_xor_44()
//     { }
//     function test_xor_45()
//     { }
//     function test_xor_46()
//     { }
//     function test_xor_47()
//     { }
//     function test_xor_48()
//     { }
//     function test_byte_0()
//     { }
//     function test_byte_1()
//     { }
//     function test_byte_2()
//     { }
//     function test_byte_3()
//     { }
//     function test_byte_4()
//     { }
//     function test_byte_5()
//     { }
//     function test_byte_6()
//     { }
//     function test_byte_7()
//     { }
//     function test_byte_8()
//     { }
//     function test_byte_9()
//     { }
//     function test_byte_10()
//     { }
//     function test_byte_11()
//     { }
//     function test_byte_12()
//     { }
//     function test_byte_13()
//     { }
//     function test_byte_14()
//     { }
//     function test_byte_15()
//     { }
//     function test_byte_16()
//     { }
//     function test_byte_17()
//     { }
//     function test_byte_18()
//     { }
//     function test_byte_19()
//     { }
//     function test_byte_20()
//     { }
//     function test_byte_21()
//     { }
//     function test_byte_22()
//     { }
//     function test_byte_23()
//     { }
//     function test_byte_24()
//     { }
//     function test_shl_0()
//     { }
//     function test_shl_1()
//     { }
//     function test_shl_2()
//     { }
//     function test_shl_3()
//     { }
//     function test_shl_4()
//     { }
//     function test_shl_5()
//     { }
//     function test_shl_6()
//     { }
//     function test_shl_7()
//     { }
//     function test_shl_8()
//     { }
//     function test_shl_9()
//     { }
//     function test_shl_10()
//     { }
//     function test_shl_11()
//     { }
//     function test_shl_12()
//     { }
//     function test_shl_13()
//     { }
//     function test_shl_14()
//     { }
//     function test_shl_15()
//     { }
//     function test_shl_16()
//     { }
//     function test_shl_17()
//     { }
//     function test_shl_18()
//     { }
//     function test_shl_19()
//     { }
//     function test_shl_20()
//     { }
//     function test_shl_21()
//     { }
//     function test_shl_22()
//     { }
//     function test_shl_23()
//     { }
//     function test_shl_24()
//     { }
//     function test_shl_25()
//     { }
//     function test_shl_26()
//     { }
//     function test_shl_27()
//     { }
//     function test_shl_28()
//     { }
//     function test_shl_29()
//     { }
//     function test_shl_30()
//     { }
//     function test_shl_31()
//     { }
//     function test_shl_32()
//     { }
//     function test_shl_33()
//     { }
//     function test_shl_34()
//     { }
//     function test_shl_35()
//     { }
//     function test_shl_36()
//     { }
//     function test_shl_37()
//     { }
//     function test_shl_38()
//     { }
//     function test_shl_39()
//     { }
//     function test_shl_40()
//     { }
//     function test_shl_41()
//     { }
//     function test_shl_42()
//     { }
//     function test_shl_43()
//     { }
//     function test_shl_44()
//     { }
//     function test_shl_45()
//     { }
//     function test_shl_46()
//     { }
//     function test_shl_47()
//     { }
//     function test_shl_48()
//     { }
//     function test_shr_0()
//     { }
//     function test_shr_1()
//     { }
//     function test_shr_2()
//     { }
//     function test_shr_3()
//     { }
//     function test_shr_4()
//     { }
//     function test_shr_5()
//     { }
//     function test_shr_6()
//     { }
//     function test_shr_7()
//     { }
//     function test_shr_8()
//     { }
//     function test_shr_9()
//     { }
//     function test_shr_10()
//     { }
//     function test_shr_11()
//     { }
//     function test_shr_12()
//     { }
//     function test_shr_13()
//     { }
//     function test_shr_14()
//     { }
//     function test_shr_15()
//     { }
//     function test_shr_16()
//     { }
//     function test_shr_17()
//     { }
//     function test_shr_18()
//     { }
//     function test_shr_19()
//     { }
//     function test_shr_20()
//     { }
//     function test_shr_21()
//     { }
//     function test_shr_22()
//     { }
//     function test_shr_23()
//     { }
//     function test_shr_24()
//     { }
//     function test_shr_25()
//     { }
//     function test_shr_26()
//     { }
//     function test_shr_27()
//     { }
//     function test_shr_28()
//     { }
//     function test_shr_29()
//     { }
//     function test_shr_30()
//     { }
//     function test_shr_31()
//     { }
//     function test_shr_32()
//     { }
//     function test_shr_33()
//     { }
//     function test_shr_34()
//     { }
//     function test_shr_35()
//     { }
//     function test_shr_36()
//     { }
//     function test_shr_37()
//     { }
//     function test_shr_38()
//     { }
//     function test_shr_39()
//     { }
//     function test_shr_40()
//     { }
//     function test_shr_41()
//     { }
//     function test_shr_42()
//     { }
//     function test_shr_43()
//     { }
//     function test_shr_44()
//     { }
//     function test_shr_45()
//     { }
//     function test_shr_46()
//     { }
//     function test_shr_47()
//     { }
//     function test_shr_48()
//     { }
//     function test_sar_0()
//     { }
//     function test_sar_1()
//     { }
//     function test_sar_2()
//     { }
//     function test_sar_3()
//     { }
//     function test_sar_4()
//     { }
//     function test_sar_5()
//     { }
//     function test_sar_6()
//     { }
//     function test_sar_7()
//     { }
//     function test_sar_8()
//     { }
//     function test_sar_9()
//     { }
//     function test_sar_10()
//     { }
//     function test_sar_11()
//     { }
//     function test_sar_12()
//     { }
//     function test_sar_13()
//     { }
//     function test_sar_14()
//     { }
//     function test_sar_15()
//     { }
//     function test_sar_16()
//     { }
//     function test_sar_17()
//     { }
//     function test_sar_18()
//     { }
//     function test_sar_19()
//     { }
//     function test_sar_20()
//     { }
//     function test_sar_21()
//     { }
//     function test_sar_22()
//     { }
//     function test_sar_23()
//     { }
//     function test_sar_24()
//     { }
//     function test_sar_25()
//     { }
//     function test_sar_26()
//     { }
//     function test_sar_27()
//     { }
//     function test_sar_28()
//     { }
//     function test_sar_29()
//     { }
//     function test_sar_30()
//     { }
//     function test_sar_31()
//     { }
//     function test_sar_32()
//     { }
//     function test_sar_33()
//     { }
//     function test_sar_34()
//     { }
//     function test_sar_35()
//     { }
//     function test_sar_36()
//     { }
//     function test_sar_37()
//     { }
//     function test_sar_38()
//     { }
//     function test_sar_39()
//     { }
//     function test_sar_40()
//     { }
//     function test_sar_41()
//     { }
//     function test_sar_42()
//     { }
//     function test_sar_43()
//     { }
//     function test_sar_44()
//     { }
//     function test_sar_45()
//     { }
//     function test_sar_46()
//     { }
//     function test_sar_47()
//     { }
//     function test_sar_48()
//     { }
//     function test_addmod_0()
//     { }
//     function test_addmod_1()
//     { }
//     function test_addmod_2()
//     { }
//     function test_addmod_3()
//     { }
//     function test_addmod_4()
//     { }
//     function test_addmod_5()
//     { }
//     function test_addmod_6()
//     { }
//     function test_addmod_7()
//     { }
//     function test_addmod_8()
//     { }
//     function test_addmod_9()
//     { }
//     function test_addmod_10()
//     { }
//     function test_addmod_11()
//     { }
//     function test_addmod_12()
//     { }
//     function test_addmod_13()
//     { }
//     function test_addmod_14()
//     { }
//     function test_addmod_15()
//     { }
//     function test_addmod_16()
//     { }
//     function test_addmod_17()
//     { }
//     function test_addmod_18()
//     { }
//     function test_addmod_19()
//     { }
//     function test_addmod_20()
//     { }
//     function test_addmod_21()
//     { }
//     function test_addmod_22()
//     { }
//     function test_addmod_23()
//     { }
//     function test_addmod_24()
//     { }
//     function test_addmod_25()
//     { }
//     function test_addmod_26()
//     { }
//     function test_addmod_27()
//     { }
//     function test_addmod_28()
//     { }
//     function test_addmod_29()
//     { }
//     function test_addmod_30()
//     { }
//     function test_addmod_31()
//     { }
//     function test_addmod_32()
//     { }
//     function test_addmod_33()
//     { }
//     function test_addmod_34()
//     { }
//     function test_addmod_35()
//     { }
//     function test_addmod_36()
//     { }
//     function test_addmod_37()
//     { }
//     function test_addmod_38()
//     { }
//     function test_addmod_39()
//     { }
//     function test_addmod_40()
//     { }
//     function test_addmod_41()
//     { }
//     function test_addmod_42()
//     { }
//     function test_addmod_43()
//     { }
//     function test_addmod_44()
//     { }
//     function test_addmod_45()
//     { }
//     function test_addmod_46()
//     { }
//     function test_addmod_47()
//     { }
//     function test_addmod_48()
//     { }
//     function test_addmod_49()
//     { }
//     function test_addmod_50()
//     { }
//     function test_addmod_51()
//     { }
//     function test_addmod_52()
//     { }
//     function test_addmod_53()
//     { }
//     function test_addmod_54()
//     { }
//     function test_addmod_55()
//     { }
//     function test_addmod_56()
//     { }
//     function test_addmod_57()
//     { }
//     function test_addmod_58()
//     { }
//     function test_addmod_59()
//     { }
//     function test_addmod_60()
//     { }
//     function test_addmod_61()
//     { }
//     function test_addmod_62()
//     { }
//     function test_addmod_63()
//     { }
//     function test_mulmod_0()
//     { }
//     function test_mulmod_1()
//     { }
//     function test_mulmod_2()
//     { }
//     function test_mulmod_3()
//     { }
//     function test_mulmod_4()
//     { }
//     function test_mulmod_5()
//     { }
//     function test_mulmod_6()
//     { }
//     function test_mulmod_7()
//     { }
//     function test_mulmod_8()
//     { }
//     function test_mulmod_9()
//     { }
//     function test_mulmod_10()
//     { }
//     function test_mulmod_11()
//     { }
//     function test_mulmod_12()
//     { }
//     function test_mulmod_13()
//     { }
//     function test_mulmod_14()
//     { }
//     function test_mulmod_15()
//     { }
//     function test_mulmod_16()
//     { }
//     function test_mulmod_17()
//     { }
//     function test_mulmod_18()
//     { }
//     function test_mulmod_19()
//     { }
//     function test_mulmod_20()
//     { }
//     function test_mulmod_21()
//     { }
//     function test_mulmod_22()
//     { }
//     function test_mulmod_23()
//     { }
//     function test_mulmod_24()
//     { }
//     function test_mulmod_25()
//     { }
//     function test_mulmod_26()
//     { }
//     function test_mulmod_27()
//     { }
//     function test_mulmod_28()
//     { }
//     function test_mulmod_29()
//     { }
//     function test_mulmod_30()
//     { }
//     function test_mulmod_31()
//     { }
//     function test_mulmod_32()
//     { }
//     function test_mulmod_33()
//     { }
//     function test_mulmod_34()
//     { }
//     function test_mulmod_35()
//     { }
//     function test_mulmod_36()
//     { }
//     function test_mulmod_37()
//     { }
//     function test_mulmod_38()
//     { }
//     function test_mulmod_39()
//     { }
//     function test_mulmod_40()
//     { }
//     function test_mulmod_41()
//     { }
//     function test_mulmod_42()
//     { }
//     function test_mulmod_43()
//     { }
//     function test_mulmod_44()
//     { }
//     function test_mulmod_45()
//     { }
//     function test_mulmod_46()
//     { }
//     function test_mulmod_47()
//     { }
//     function test_mulmod_48()
//     { }
//     function test_mulmod_49()
//     { }
//     function test_mulmod_50()
//     { }
//     function test_mulmod_51()
//     { }
//     function test_mulmod_52()
//     { }
//     function test_mulmod_53()
//     { }
//     function test_mulmod_54()
//     { }
//     function test_mulmod_55()
//     { }
//     function test_mulmod_56()
//     { }
//     function test_mulmod_57()
//     { }
//     function test_mulmod_58()
//     { }
//     function test_mulmod_59()
//     { }
//     function test_mulmod_60()
//     { }
//     function test_mulmod_61()
//     { }
//     function test_mulmod_62()
//     { }
//     function test_mulmod_63()
//     { }
//     function test_signextend_0()
//     { }
//     function test_signextend_1()
//     { }
//     function test_signextend_2()
//     { }
//     function test_signextend_3()
//     { }
//     function test_signextend_4()
//     { }
//     function test_signextend_5()
//     { }
//     function test_signextend_6()
//     { }
//     function test_signextend_7()
//     { }
//     function test_signextend_8()
//     { }
//     function test_signextend_9()
//     { }
//     function test_signextend_10()
//     { }
//     function test_signextend_11()
//     { }
//     function test_signextend_12()
//     { }
//     function test_signextend_13()
//     { }
//     function test_signextend_14()
//     { }
//     function test_signextend_15()
//     { }
//     function test_signextend_16()
//     { }
//     function test_signextend_17()
//     { }
//     function test_signextend_18()
//     { }
//     function test_signextend_19()
//     { }
//     function test_signextend_20()
//     { }
//     function test_signextend_21()
//     { }
//     function test_signextend_22()
//     { }
//     function test_signextend_23()
//     { }
//     function test_signextend_24()
//     { }
//     function test_signextend_25()
//     { }
//     function test_signextend_26()
//     { }
//     function test_signextend_27()
//     { }
//     function test_signextend_28()
//     { }
//     function test_signextend_29()
//     { }
//     function test_signextend_30()
//     { }
//     function test_signextend_31()
//     { }
//     function test_signextend_32()
//     { }
//     function test_signextend_33()
//     { }
//     function test_signextend_34()
//     { }
//     function test_signextend_35()
//     { }
//     function test_signextend_36()
//     { }
//     function test_signextend_37()
//     { }
//     function test_signextend_38()
//     { }
//     function test_signextend_39()
//     { }
//     function test_signextend_40()
//     { }
//     function test_signextend_41()
//     { }
//     function test_signextend_42()
//     { }
//     function test_signextend_43()
//     { }
//     function test_signextend_44()
//     { }
//     function test_signextend_45()
//     { }
//     function test_signextend_46()
//     { }
//     function test_signextend_47()
//     { }
//     function test_signextend_48()
//     { }
// }
