(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

(* Contract *)
Module C.
  Definition g (α : list Value.t) : M :=
    match α with
    | [] =>
      let _ :=
        M.define (|
          [ "w" ],
          M.call (|
            M.get_name (| "blobhash" |),
            [
              Value.Integer 0
            ]
          |)
        |) in
      let _ :=
        M.get_name (| "w" |) in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End C.
