{ let z := 0 switch z case 0 { let x := 2 let y := 3 } default { z := 3 } let t := 9 }
// ====
// stackOptimization: true
// ----
//     /* "":11:12   */
//   0x00
//     /* "":27:28   */
//   0x00
//     /* "":22:54   */
//   eq
//   tag_1
//   jumpi
//     /* "":13:73   */
// tag_2:
//     /* "":70:71   */
//   0x03
//     /* "":63:73   */
//   pop
//     /* "":13:73   */
// tag_3:
//     /* "":83:84   */
//   0x09
//     /* "":13:73   */
//   stop
//     /* "":29:54   */
// tag_1:
//     /* "":40:41   */
//   0x02
//     /* "":42:52   */
//   pop
//     /* "":51:52   */
//   0x03
//     /* "":29:54   */
//   pop
//   jump(tag_3)
