contract Main {
    struct B { C m; }
    struct C { D m; }
    struct D { E m; }
    struct E { F m; }
    struct F { G m; }
    struct G { H m; }
    struct H { I m; }
    struct I { J m; }
    struct J { K m; }
    struct K { L m; }
    struct L { M m; }
    struct M { N m; }
    struct N { O m; }
    struct O { P m; }
    struct P { Q m; }
    struct Q { R m; }
    struct R { S m; }
    struct S { T m; }
    struct T { U m; }
    struct U { V m; }
    struct V { W m; }
    struct W { X m; }
    struct X { Y m; }
    struct Y { Z m; }
    struct Z { BA m; }
    struct BA { BB m; }
    struct BB { BC m; }
    struct BC { BD m; }
    struct BD { BE m; }
    struct BE { BF m; }
    struct BF { BG m; }
    struct BG { BH m; }
    struct BH { BI m; }
    struct BI { BJ m; }
    struct BJ { BK m; }
    struct BK { BL m; }
    struct BL { BM m; }
    struct BM { BN m; }
    struct BN { BO m; }
    struct BO { BP m; }
    struct BP { BQ m; }
    struct BQ { BR m; }
    struct BR { BS m; }
    struct BS { BT m; }
    struct BT { BU m; }
    struct BU { BV m; }
    struct BV { BW m; }
    struct BW { BX m; }
    struct BX { BY m; }
    struct BY { BZ m; }
    struct BZ { CA m; }
    struct CA { CB m; }
    struct CB { CC m; }
    struct CC { CD m; }
    struct CD { CE m; }
    struct CE { CF m; }
    struct CF { CG m; }
    struct CG { CH m; }
    struct CH { CI m; }
    struct CI { CJ m; }
    struct CJ { CK m; }
    struct CK { CL m; }
    struct CL { CM m; }
    struct CM { CN m; }
    struct CN { CO m; }
    struct CO { CP m; }
    struct CP { CQ m; }
    struct CQ { CR m; }
    struct CR { CS m; }
    struct CS { CT m; }
    struct CT { CU m; }
    struct CU { CV m; }
    struct CV { CW m; }
    struct CW { CX m; }
    struct CX { CY m; }
    struct CY { CZ m; }
    struct CZ { DA m; }
    struct DA { DB m; }
    struct DB { DC m; }
    struct DC { DD m; }
    struct DD { DE m; }
    struct DE { DF m; }
    struct DF { DG m; }
    struct DG { DH m; }
    struct DH { DI m; }
    struct DI { DJ m; }
    struct DJ { DK m; }
    struct DK { DL m; }
    struct DL { DM m; }
    struct DM { DN m; }
    struct DN { DO m; }
    struct DO { DP m; }
    struct DP { DQ m; }
    struct DQ { DR m; }
    struct DR { DS m; }
    struct DS { DT m; }
    struct DT { DU m; }
    struct DU { DV m; }
    struct DV { DW m; }
    struct DW { DX m; }
    struct DX { DY m; }
    struct DY { DZ m; }
    struct DZ { EA m; }
    struct EA { EB m; }
    struct EB { EC m; }
    struct EC { ED m; }
    struct ED { EE m; }
    struct EE { EF m; }
    struct EF { EG m; }
    struct EG { EH m; }
    struct EH { EI m; }
    struct EI { EJ m; }
    struct EJ { EK m; }
    struct EK { EL m; }
    struct EL { EM m; }
    struct EM { EN m; }
    struct EN { EO m; }
    struct EO { EP m; }
    struct EP { EQ m; }
    struct EQ { ER m; }
    struct ER { ES m; }
    struct ES { ET m; }
    struct ET { EU m; }
    struct EU { EV m; }
    struct EV { EW m; }
    struct EW { EX m; }
    struct EX { EY m; }
    struct EY { EZ m; }
    struct EZ { FA m; }
    struct FA { FB m; }
    struct FB { FC m; }
    struct FC { FD m; }
    struct FD { FE m; }
    struct FE { FF m; }
    struct FF { FG m; }
    struct FG { FH m; }
    struct FH { FI m; }
    struct FI { FJ m; }
    struct FJ { FK m; }
    struct FK { FL m; }
    struct FL { FM m; }
    struct FM { FN m; }
    struct FN { FO m; }
    struct FO { FP m; }
    struct FP { FQ m; }
    struct FQ { FR m; }
    struct FR { FS m; }
    struct FS { FT m; }
    struct FT { FU m; }
    struct FU { FV m; }
    struct FV { FW m; }
    struct FW { FX m; }
    struct FX { FY m; }
    struct FY { FZ m; }
    struct FZ { GA m; }
    struct GA { GB m; }
    struct GB { GC m; }
    struct GC { GD m; }
    struct GD { GE m; }
    struct GE { GF m; }
    struct GF { GG m; }
    struct GG { GH m; }
    struct GH { GI m; }
    struct GI { GJ m; }
    struct GJ { GK m; }
    struct GK { GL m; }
    struct GL { GM m; }
    struct GM { GN m; }
    struct GN { GO m; }
    struct GO { GP m; }
    struct GP { GQ m; }
    struct GQ { GR m; }
    struct GR { GS m; }
    struct GS { GT m; }
    struct GT { GU m; }
    struct GU { GV m; }
    struct GV { GW m; }
    struct GW { GX m; }
    struct GX { GY m; }
    struct GY { GZ m; }
    struct GZ { HA m; }
    struct HA { HB m; }
    struct HB { HC m; }
    struct HC { HD m; }
    struct HD { HE m; }
    struct HE { HF m; }
    struct HF { HG m; }
    struct HG { HH m; }
    struct HH { HI m; }
    struct HI { HJ m; }
    struct HJ { HK m; }
    struct HK { HL m; }
    struct HL { HM m; }
    struct HM { HN m; }
    struct HN { HO m; }
    struct HO { HP m; }
    struct HP { HQ m; }
    struct HQ { HR m; }
    struct HR { HS m; }
    struct HS { HT m; }
    struct HT { HU m; }
    struct HU { HV m; }
    struct HV { HW m; }
    struct HW { HX m; }
    struct HX { HY m; }
    struct HY { HZ m; }
    struct HZ { IA m; }
    struct IA { IB m; }
    struct IB { IC m; }
    struct IC { ID m; }
    struct ID { IE m; }
    struct IE { IF m; }
    struct IF { IG m; }
    struct IG { IH m; }
    struct IH { II m; }
    struct II { IJ m; }
    struct IJ { IK m; }
    struct IK { IL m; }
    struct IL { IM m; }
    struct IM { IN m; }
    struct IN { IO m; }
    struct IO { IP m; }
    struct IP { IQ m; }
    struct IQ { IR m; }
    struct IR { IS m; }
    struct IS { IT m; }
    struct IT { IU m; }
    struct IU { IV m; }
    struct IV { IW m; }
    struct IW { IX m; }
    struct IX { IY m; }
    struct IY { IZ m; }
    struct IZ { JA m; }
    struct JA { JB m; }
    struct JB { JC m; }
    struct JC { JD m; }
    struct JD { JE m; }
    struct JE { JF m; }
    struct JF { JG m; }
    struct JG { JH m; }
    struct JH { JI m; }
    struct JI { JJ m; }
    struct JJ { JK m; }
    struct JK { JL m; }
    struct JL { JM m; }
    struct JM { JN m; }
    struct JN { JO m; }
    struct JO { JP m; }
    struct JP { JQ m; }
    struct JQ { JR m; }
    struct JR { JS m; }
    struct JS { JT m; }
    struct JT { JU m; }
    struct JU { JV m; }
    struct JV { JW m; }
    struct JW { int i; }
}
// ----
// DeclarationError: (6091-6111): Struct definition exhausting cyclic dependency validator.
