contract Main {
    struct B { C m; }
    struct C { D m; }
    struct D { E m; }
    struct E { F m; }
    struct F { G m; }
    struct G { H m; }
    struct H { I m; }
    struct I { J m; }
    struct J { K m; }
    struct K { L m; }
    struct L { M m; }
    struct M { N m; }
    struct N { O m; }
    struct O { P m; }
    struct P { Q m; }
    struct Q { R m; }
    struct R { S m; }
    struct S { T m; }
    struct T { U m; }
    struct U { V m; }
    struct V { W m; }
    struct W { X m; }
    struct X { Y m; }
    struct Y { Z m; }
    struct Z { BA m; }
    struct BA { BB m; }
    struct BB { BC m; }
    struct BC { BD m; }
    struct BD { BE m; }
    struct BE { BF m; }
    struct BF { BG m; }
    struct BG { BH m; }
    struct BH { BI m; }
    struct BI { BJ m; }
    struct BJ { BK m; }
    struct BK { BL m; }
    struct BL { BM m; }
    struct BM { BN m; }
    struct BN { BO m; }
    struct BO { BP m; }
    struct BP { BQ m; }
    struct BQ { BR m; }
    struct BR { BS m; }
    struct BS { BT m; }
    struct BT { BU m; }
    struct BU { BV m; }
    struct BV { BW m; }
    struct BW { BX m; }
    struct BX { BY m; }
    struct BY { BZ m; }
    struct BZ { CA m; }
    struct CA { CB m; }
    struct CB { CC m; }
    struct CC { CD m; }
    struct CD { CE m; }
    struct CE { CF m; }
    struct CF { CG m; }
    struct CG { CH m; }
    struct CH { CI m; }
    struct CI { CJ m; }
    struct CJ { CK m; }
    struct CK { CL m; }
    struct CL { CM m; }
    struct CM { CN m; }
    struct CN { CO m; }
    struct CO { CP m; }
    struct CP { CQ m; }
    struct CQ { CR m; }
    struct CR { CS m; }
    struct CS { CT m; }
    struct CT { CU m; }
    struct CU { CV m; }
    struct CV { CW m; }
    struct CW { CX m; }
    struct CX { CY m; }
    struct CY { CZ m; }
    struct CZ { DA m; }
    struct DA { DB m; }
    struct DB { DC m; }
    struct DC { DD m; }
    struct DD { DE m; }
    struct DE { DF m; }
    struct DF { DG m; }
    struct DG { DH m; }
    struct DH { DI m; }
    struct DI { DJ m; }
    struct DJ { DK m; }
    struct DK { DL m; }
    struct DL { DM m; }
    struct DM { DN m; }
    struct DN { DO m; }
    struct DO { DP m; }
    struct DP { DQ m; }
    struct DQ { DR m; }
    struct DR { DS m; }
    struct DS { DT m; }
    struct DT { DU m; }
    struct DU { DV m; }
    struct DV { DW m; }
    struct DW { DX m; }
    struct DX { DY m; }
    struct DY { DZ m; }
    struct DZ { EA m; }
    struct EA { EB m; }
    struct EB { EC m; }
    struct EC { ED m; }
    struct ED { EE m; }
    struct EE { EF m; }
    struct EF { EG m; }
    struct EG { EH m; }
    struct EH { EI m; }
    struct EI { EJ m; }
    struct EJ { EK m; }
    struct EK { EL m; }
    struct EL { EM m; }
    struct EM { EN m; }
    struct EN { EO m; }
    struct EO { EP m; }
    struct EP { EQ m; }
    struct EQ { ER m; }
    struct ER { ES m; }
    struct ES { ET m; }
    struct ET { EU m; }
    struct EU { EV m; }
    struct EV { EW m; }
    struct EW { EX m; }
    struct EX { EY m; }
    struct EY { EZ m; }
    struct EZ { FA m; }
    struct FA { FB m; }
    struct FB { FC m; }
    struct FC { int i; }
}
