(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

Module C.
  Definition code : Code.t := {|
    Code.name := "C_60";
    Code.hex_name := 0x435f363000000000000000000000000000000000000000000000000000000000;
    Code.functions :=
      [
        
      ];
    Code.body :=
      M.scope (
        do! ltac:(M.monadic (
          M.scope (
            do! ltac:(M.monadic (
              M.declare (|
                ["_1"],
                Some (M.call_function (|
                  "memoryguard",
                  [
                    [Literal.number 0x80]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "mstore",
                  [
                    [Literal.number 64];
                    M.get_var (| "_1" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.if_ (|
                M.call_function (|
                  "callvalue",
                  []
                |),
                M.scope (
                  do! ltac:(M.monadic (
                    M.expr_stmt (|
                      M.call_function (|
                        "revert",
                        [
                          [Literal.number 0];
                          [Literal.number 0]
                        ]
                      |)
                    |)
                  )) in
                  M.pure BlockUnit.Tt
                )
              |)
            )) in
            do! ltac:(M.monadic (
              M.declare (|
                ["_2"],
                Some (M.call_function (|
                  "datasize",
                  [
                    [Literal.string 0x435f36305f6465706c6f79656400000000000000000000000000000000000000]
                  ]
                |))
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "codecopy",
                  [
                    M.get_var (| "_1" |);
                    M.call_function (|
                      "dataoffset",
                      [
                        [Literal.string 0x435f36305f6465706c6f79656400000000000000000000000000000000000000]
                      ]
                    |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            do! ltac:(M.monadic (
              M.expr_stmt (|
                M.call_function (|
                  "return",
                  [
                    M.get_var (| "_1" |);
                    M.get_var (| "_2" |)
                  ]
                |)
              |)
            )) in
            M.pure BlockUnit.Tt
          )
        )) in
        M.pure BlockUnit.Tt
      );
  |}.

  Module deployed.
    Definition code : Code.t := {|
      Code.name := "C_60_deployed";
      Code.hex_name := 0x435f36305f6465706c6f79656400000000000000000000000000000000000000;
      Code.functions :=
        [
          Code.Function.make (
            "finalize_allocation",
            ["memPtr"; "size"],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.declare (|
                  ["newFreePtr"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "memPtr" |);
                      M.call_function (|
                        "and",
                        [
                          M.call_function (|
                            "add",
                            [
                              M.get_var (| "size" |);
                              [Literal.number 31]
                            ]
                          |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 31]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "or",
                    [
                      M.call_function (|
                        "gt",
                        [
                          M.get_var (| "newFreePtr" |);
                          [Literal.number 0xffffffffffffffff]
                        ]
                      |);
                      M.call_function (|
                        "lt",
                        [
                          M.get_var (| "newFreePtr" |);
                          M.get_var (| "memPtr" |)
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 0];
                            M.call_function (|
                              "shl",
                              [
                                [Literal.number 224];
                                [Literal.number 0x4e487b71]
                              ]
                            |)
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 4];
                            [Literal.number 0x41]
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0x24]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 64];
                      M.get_var (| "newFreePtr" |)
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "abi_decode_array_uint256_dynt_array_uint256_calldata",
            ["dataEnd"],
            ["value0"; "value1"],
            M.scope (
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "slt",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "dataEnd" |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 3]
                            ]
                          |)
                        ]
                      |);
                      [Literal.number 64]
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["offset"],
                  Some (M.call_function (|
                    "calldataload",
                    [
                      [Literal.number 4]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "gt",
                    [
                      M.get_var (| "offset" |);
                      [Literal.number 0xffffffffffffffff]
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "iszero",
                    [
                      M.call_function (|
                        "slt",
                        [
                          M.call_function (|
                            "add",
                            [
                              M.get_var (| "offset" |);
                              [Literal.number 35]
                            ]
                          |);
                          M.get_var (| "dataEnd" |)
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["length"],
                  Some (M.call_function (|
                    "calldataload",
                    [
                      M.call_function (|
                        "add",
                        [
                          [Literal.number 4];
                          M.get_var (| "offset" |)
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "gt",
                    [
                      M.get_var (| "length" |);
                      [Literal.number 0xffffffffffffffff]
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 0];
                            M.call_function (|
                              "shl",
                              [
                                [Literal.number 224];
                                [Literal.number 0x4e487b71]
                              ]
                            |)
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "mstore",
                          [
                            [Literal.number 4];
                            [Literal.number 0x41]
                          ]
                        |)
                      |)
                    )) in
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 36]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["_1"],
                  Some (M.call_function (|
                    "shl",
                    [
                      [Literal.number 5];
                      M.get_var (| "length" |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["memPtr"],
                  Some (M.call_function (|
                    "mload",
                    [
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "finalize_allocation",
                    [
                      M.get_var (| "memPtr" |);
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "_1" |);
                          [Literal.number 0x20]
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["dst"],
                  Some (M.get_var (| "memPtr" |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "memPtr" |);
                      M.get_var (| "length" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["dst"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "memPtr" |);
                      [Literal.number 0x20]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["srcEnd"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "offset" |);
                          M.get_var (| "_1" |)
                        ]
                      |);
                      [Literal.number 36]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "gt",
                    [
                      M.get_var (| "srcEnd" |);
                      M.get_var (| "dataEnd" |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["src"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "offset" |);
                      [Literal.number 36]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                do!
                  M.scope (
                    M.pure BlockUnit.Tt
                  ) in
                ltac:(M.monadic (
                  M.for_ (|
                    ltac:(M.monadic (
                      M.call_function (|
                        "lt",
                        [
                          M.get_var (| "src" |);
                          M.get_var (| "srcEnd" |)
                        ]
                      |)
                    )),
                    M.scope (
                      do! ltac:(M.monadic (
                        M.assign (|
                          ["src"],
                          Some (M.call_function (|
                            "add",
                            [
                              M.get_var (| "src" |);
                              [Literal.number 0x20]
                            ]
                          |))
                        |)
                      )) in
                      M.pure BlockUnit.Tt
                    ),
                    M.scope (
                      do! ltac:(M.monadic (
                        M.expr_stmt (|
                          M.call_function (|
                            "mstore",
                            [
                              M.get_var (| "dst" |);
                              M.call_function (|
                                "calldataload",
                                [
                                  M.get_var (| "src" |)
                                ]
                              |)
                            ]
                          |)
                        |)
                      )) in
                      do! ltac:(M.monadic (
                        M.assign (|
                          ["dst"],
                          Some (M.call_function (|
                            "add",
                            [
                              M.get_var (| "dst" |);
                              [Literal.number 0x20]
                            ]
                          |))
                        |)
                      )) in
                      M.pure BlockUnit.Tt
                    )
                  |)
                ))
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["value0"],
                  Some (M.get_var (| "memPtr" |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "gt",
                    [
                      [Literal.number 68];
                      M.get_var (| "dataEnd" |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["value1"],
                  Some ([Literal.number 36])
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "external_fun_g",
            [],
            [],
            M.scope (
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "callvalue",
                    []
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.expr_stmt (|
                        M.call_function (|
                          "revert",
                          [
                            [Literal.number 0];
                            [Literal.number 0]
                          ]
                        |)
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["param"; "param_1"],
                  Some (M.call_function (|
                    "abi_decode_array_uint256_dynt_array_uint256_calldata",
                    [
                      M.call_function (|
                        "calldatasize",
                        []
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["var_mpos"],
                  Some ([Literal.number 0])
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["expr_mpos"],
                  Some (M.call_function (|
                    "mload",
                    [
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["_1"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "expr_mpos" |);
                      [Literal.number 0x20]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["_2"],
                  Some (M.call_function (|
                    "sub",
                    [
                      M.call_function (|
                        "abi_encode_array_uint256_dyn_array_uint256_calldata",
                        [
                          M.get_var (| "_1" |);
                          M.get_var (| "param" |);
                          M.get_var (| "param_1" |)
                        ]
                      |);
                      M.get_var (| "expr_mpos" |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "expr_mpos" |);
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "_2" |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 31]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "finalize_allocation",
                    [
                      M.get_var (| "expr_mpos" |);
                      M.get_var (| "_2" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["var_mpos"],
                  Some (M.get_var (| "expr_mpos" |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["memPos"],
                  Some (M.call_function (|
                    "mload",
                    [
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["tail"],
                  Some ([Literal.number 0])
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "memPos" |);
                      [Literal.number 0x20]
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["length"],
                  Some (M.call_function (|
                    "mload",
                    [
                      M.get_var (| "expr_mpos" |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "memPos" |);
                          [Literal.number 0x20]
                        ]
                      |);
                      M.get_var (| "length" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mcopy",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "memPos" |);
                          [Literal.number 64]
                        ]
                      |);
                      M.get_var (| "_1" |);
                      M.get_var (| "length" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.call_function (|
                            "add",
                            [
                              M.get_var (| "memPos" |);
                              M.get_var (| "length" |)
                            ]
                          |);
                          [Literal.number 64]
                        ]
                      |);
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["_3"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "memPos" |);
                      M.call_function (|
                        "and",
                        [
                          M.call_function (|
                            "add",
                            [
                              M.get_var (| "length" |);
                              [Literal.number 31]
                            ]
                          |);
                          M.call_function (|
                            "not",
                            [
                              [Literal.number 31]
                            ]
                          |)
                        ]
                      |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["tail"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "_3" |);
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "return",
                    [
                      M.get_var (| "memPos" |);
                      M.call_function (|
                        "add",
                        [
                          M.call_function (|
                            "sub",
                            [
                              M.get_var (| "_3" |);
                              M.get_var (| "memPos" |)
                            ]
                          |);
                          [Literal.number 64]
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          );
          Code.Function.make (
            "abi_encode_array_uint256_dyn_array_uint256_calldata",
            ["headStart"; "value0"; "value1"],
            ["tail"],
            M.scope (
              do! ltac:(M.monadic (
                M.declare (|
                  ["tail_1"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "headStart" |);
                      [Literal.number 64]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "headStart" |);
                      [Literal.number 64]
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["pos"],
                  Some (M.get_var (| "tail_1" |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["length"],
                  Some (M.call_function (|
                    "mload",
                    [
                      M.get_var (| "value0" |)
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      M.get_var (| "tail_1" |);
                      M.get_var (| "length" |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["pos"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "headStart" |);
                      [Literal.number 96]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["srcPtr"],
                  Some (M.call_function (|
                    "add",
                    [
                      M.get_var (| "value0" |);
                      [Literal.number 0x20]
                    ]
                  |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.declare (|
                  ["i"],
                  Some ([Literal.number 0])
                |)
              )) in
              do! ltac:(M.monadic (
                do!
                  M.scope (
                    M.pure BlockUnit.Tt
                  ) in
                ltac:(M.monadic (
                  M.for_ (|
                    ltac:(M.monadic (
                      M.call_function (|
                        "lt",
                        [
                          M.get_var (| "i" |);
                          M.get_var (| "length" |)
                        ]
                      |)
                    )),
                    M.scope (
                      do! ltac:(M.monadic (
                        M.assign (|
                          ["i"],
                          Some (M.call_function (|
                            "add",
                            [
                              M.get_var (| "i" |);
                              [Literal.number 1]
                            ]
                          |))
                        |)
                      )) in
                      M.pure BlockUnit.Tt
                    ),
                    M.scope (
                      do! ltac:(M.monadic (
                        M.expr_stmt (|
                          M.call_function (|
                            "mstore",
                            [
                              M.get_var (| "pos" |);
                              M.call_function (|
                                "mload",
                                [
                                  M.get_var (| "srcPtr" |)
                                ]
                              |)
                            ]
                          |)
                        |)
                      )) in
                      do! ltac:(M.monadic (
                        M.assign (|
                          ["pos"],
                          Some (M.call_function (|
                            "add",
                            [
                              M.get_var (| "pos" |);
                              [Literal.number 0x20]
                            ]
                          |))
                        |)
                      )) in
                      do! ltac:(M.monadic (
                        M.assign (|
                          ["srcPtr"],
                          Some (M.call_function (|
                            "add",
                            [
                              M.get_var (| "srcPtr" |);
                              [Literal.number 0x20]
                            ]
                          |))
                        |)
                      )) in
                      M.pure BlockUnit.Tt
                    )
                  |)
                ))
              )) in
              do! ltac:(M.monadic (
                M.assign (|
                  ["tail"],
                  Some (M.get_var (| "pos" |))
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "calldatacopy",
                    [
                      M.call_function (|
                        "add",
                        [
                          M.get_var (| "headStart" |);
                          [Literal.number 0x20]
                        ]
                      |);
                      M.get_var (| "value1" |);
                      [Literal.number 0x20]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )
        ];
      Code.body :=
        M.scope (
          do! ltac:(M.monadic (
            M.scope (
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "mstore",
                    [
                      [Literal.number 64];
                      M.call_function (|
                        "memoryguard",
                        [
                          [Literal.number 0x80]
                        ]
                      |)
                    ]
                  |)
                |)
              )) in
              do! ltac:(M.monadic (
                M.if_ (|
                  M.call_function (|
                    "iszero",
                    [
                      M.call_function (|
                        "lt",
                        [
                          M.call_function (|
                            "calldatasize",
                            []
                          |);
                          [Literal.number 4]
                        ]
                      |)
                    ]
                  |),
                  M.scope (
                    do! ltac:(M.monadic (
                      M.switch (|
                        M.call_function (|
                          "shr",
                          [
                            [Literal.number 224];
                            M.call_function (|
                              "calldataload",
                              [
                                [Literal.number 0]
                              ]
                            |)
                          ]
                        |),
                        [
                          (
                            Some (Literal.number 0x599f0158),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "external_fun_g",
                                    []
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0x5e9653b9),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.if_ (|
                                  M.call_function (|
                                    "callvalue",
                                    []
                                  |),
                                  M.scope (
                                    do! ltac:(M.monadic (
                                      M.expr_stmt (|
                                        M.call_function (|
                                          "revert",
                                          [
                                            [Literal.number 0];
                                            [Literal.number 0]
                                          ]
                                        |)
                                      |)
                                    )) in
                                    M.pure BlockUnit.Tt
                                  )
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["param"; "param_1"],
                                  Some (M.call_function (|
                                    "abi_decode_array_uint256_dynt_array_uint256_calldata",
                                    [
                                      M.call_function (|
                                        "calldatasize",
                                        []
                                      |)
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.declare (|
                                  ["memPos"],
                                  Some (M.call_function (|
                                    "mload",
                                    [
                                      [Literal.number 64]
                                    ]
                                  |))
                                |)
                              )) in
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "return",
                                    [
                                      M.get_var (| "memPos" |);
                                      M.call_function (|
                                        "sub",
                                        [
                                          M.call_function (|
                                            "abi_encode_array_uint256_dyn_array_uint256_calldata",
                                            [
                                              M.get_var (| "memPos" |);
                                              M.get_var (| "param" |);
                                              M.get_var (| "param_1" |)
                                            ]
                                          |);
                                          M.get_var (| "memPos" |)
                                        ]
                                      |)
                                    ]
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          );
                          (
                            Some (Literal.number 0xe871c061),
                            M.scope (
                              do! ltac:(M.monadic (
                                M.expr_stmt (|
                                  M.call_function (|
                                    "external_fun_g",
                                    []
                                  |)
                                |)
                              )) in
                              M.pure BlockUnit.Tt
                            )
                          )
                        ]
                      |)
                    )) in
                    M.pure BlockUnit.Tt
                  )
                |)
              )) in
              do! ltac:(M.monadic (
                M.expr_stmt (|
                  M.call_function (|
                    "revert",
                    [
                      [Literal.number 0];
                      [Literal.number 0]
                    ]
                  |)
                |)
              )) in
              M.pure BlockUnit.Tt
            )
          )) in
          M.pure BlockUnit.Tt
        );
    |}.
  End deployed.
End C.

Import Ltac2.

Definition codes : list Code.t :=
  ltac2:(
    let codes := Code.get_codes () in
    exact $codes
  ).
