{
  let val := 1234567890123456789012345678901234567890123456789012345678901234567890
  val := 9876543219876543219876543219876543219876543219876543219876543219876543210
}

// ----
// step: wordSizeTransform
//
// {
//     let val_0 := 196678011949
//     let val_1 := 17592899865401375162
//     let val_2 := 3392951883154430155
//     let val_3 := 12452437124710337234
//     val_0 := 1573424111353538
//     val_1 := 11180339179422519519
//     val_2 := 5225342777609112214
//     val_3 := 12264064093151869674
// }
