{
    let x := add(999999999999999999999999999999999999999999999999999999999999999, 77777777777777777777777777777777777777777777777777777777777777)
}
// ----
// step: wordSizeTransform
//
// {
//     let _1_0 := 12390
//     let _1_1 := 13186919961226471680
//     let _1_2 := 18324050535993369984
//     let _1_3 := 15884696285694336113
//     let _2_0 := 159309
//     let _2_1 := 3525417123811528497
//     let _2_2 := 6328259118096044006
//     let _2_3 := 9223372036854775807
//     let x_0, x_1, x_2, x_3 := add(_2_0, _2_1, _2_2, _2_3, _1_0, _1_1, _1_2, _1_3)
// }
