(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

(* Contract *)
Module C.
  Definition f (α : list Value.t) : M :=
    match α with
    | [] =>
      let _ :=
        M.define (|
          [ "d1" ],
          Value.Integer 654_321
        |) in
      let _ :=
        M.define (|
          [ "d2" ],
          Value.Integer 54_321
        |) in
      let _ :=
        M.define (|
          [ "d3" ],
          Value.Integer 4_321
        |) in
      let _ :=
        M.define (|
          [ "d4" ],
          Value.Integer 5_43_21
        |) in
      let _ :=
        M.define (|
          [ "d5" ],
          Value.Integer 1_2e10
        |) in
      let _ :=
        M.define (|
          [ "d6" ],
          Value.Integer 12e1_0
        |) in
      let _ :=
        M.get_name (| "d1" |) in
      let _ :=
        M.get_name (| "d2" |) in
      let _ :=
        M.get_name (| "d3" |) in
      let _ :=
        M.get_name (| "d4" |) in
      let _ :=
        M.get_name (| "d5" |) in
      let _ :=
        M.get_name (| "d6" |) in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End C.
