(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

(* Interface *)
Module I.
  
End I.


(* Contract *)
Module E.
  
End E.


(* Library *)
Module L.
  Definition foo (α : list Value.t) : M :=
    match α with
    | [i] =>
      let _ :=
        M.return_ (|
          Value.Integer 42
        |) in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End L.


(* Contract *)
Module C.
  Axiom using : M.usingLibrary (|
      Some (Ty.path "I"),
      UsingKind.Local,
      "L"
    |).

  Definition test (α : list Value.t) : M :=
    match α with
    | [] =>
      let _ :=
        M.define (|
          [ "e" ],
          M.call (|
            NewExpression Ty.path "E"
,
            []
          |)
        |) in
      let _ :=
        M.return_ (|
          M.call (|
            M.member_access (|
              M.call (|
                M.get_name (| "I" |),
                [
                  M.get_name (| "e" |)
                ]
              |),
              "foo"
            |),
            []
          |)
        |) in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End C.
