{
  sstore(0, add(0, 1))
  sstore(1, add(1, not(0)))
  sstore(2, add(0, 0))
  sstore(3, add(1, 2))
  sstore(4, add(0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe, 1))
  sstore(5, add(
    0x8000000000000000000000000000000000000000000000000000000000000000, 1
  ))
  sstore(6, add(not(0), 1))
  sstore(7, add(0xffffffffffffffffffffffffffffffff, 1))
  sstore(8, add(0xffffffffffffffff, 1))
  sstore(9, add(0xffffffffffffffffffffffffffffffff0000000000000000, 1))
  sstore(10, add(0xffffffffffffffffffffffffffffffffffffffffffffffff, 3))
  sstore(11, add(0xffffffffffffffffffffffffffffffff, 3))
  sstore(12, add(0xffffffffffffffff, 3))
  sstore(13, add(0xffffffffffffffffffffffffffffffff0000000000000000, 3))
}
// ----
// Trace:
// Memory dump:
//      0: 000000000000000000000000000000000000000000000000000000000000000d
//     20: 0000000000000000ffffffffffffffffffffffffffffffff0000000000000003
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000003: 0000000000000000000000000000000000000000000000000000000000000003
//   0000000000000000000000000000000000000000000000000000000000000004: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
//   0000000000000000000000000000000000000000000000000000000000000005: 8000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000007: 0000000000000000000000000000000100000000000000000000000000000000
//   0000000000000000000000000000000000000000000000000000000000000008: 0000000000000000000000000000000000000000000000010000000000000000
//   0000000000000000000000000000000000000000000000000000000000000009: 0000000000000000ffffffffffffffffffffffffffffffff0000000000000001
//   000000000000000000000000000000000000000000000000000000000000000a: 0000000000000001000000000000000000000000000000000000000000000002
//   000000000000000000000000000000000000000000000000000000000000000b: 0000000000000000000000000000000100000000000000000000000000000002
//   000000000000000000000000000000000000000000000000000000000000000c: 0000000000000000000000000000000000000000000000010000000000000002
//   000000000000000000000000000000000000000000000000000000000000000d: 0000000000000000ffffffffffffffffffffffffffffffff0000000000000003
