{
  sstore(0, eq(0, 0))
  sstore(1, eq(not(0), not(0)))
  sstore(2, eq(0, not(0)))
  sstore(3, eq(not(0), 0xffffffffffffffff))
  sstore(4, eq(0xfffffffffffffff000000000000000, 0xfffffffffffffff000000000000000))
  sstore(5, eq(0x000000000000000fffffffffffffff, 0xfffffffffffffff000000000000000))
  sstore(6, eq(0xfffffffffffffff000000000000000fffffffffffffff, 0xfffffffffffffff000000000000000fffffffffffffff))
  sstore(7, eq(0xfffffffffffffff000000000000000fffffffffffffff, 0x000000000000000ffffffffffffffffffffffffffffff))
  sstore(8, eq(
    0xaaaaaaaaaaaaaaaa5555555555555555ffffffffffffffff0000000000000000,
    0xaaaaaaaaaaaaaaaa5555555555555555ffffffffffffffff0000000000000000
  ))
  sstore(9, eq(
    0xaaaaaaaaaaaaaaaa6666666666666666ffffffffffffffff0000000000000000,
    0xaaaaaaaaaaaaaaaa5555555555555555ffffffffffffffff0000000000000000
   ))
}
// ----
// Trace:
// Memory dump:
//      0: 0000000000000000000000000000000000000000000000000000000000000009
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000001: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000004: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000006: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000008: 0000000000000000000000000000000000000000000000000000000000000001
