{
  sstore(0, gt(1, 0))
  sstore(1, gt(0, 1))
  sstore(2, gt(0, 0))
  sstore(3, gt(not(0), 0xffffffffffffffff))
  sstore(4, gt(0xffffffffffffffff, not(0)))
  sstore(5, gt(not(0), not(0)))
  sstore(6, gt(not(0), 0xffffffffffffffff0000000000000000))
  sstore(7, gt(0xffffffffffffffff0000000000000000, not(0)))
  sstore(8, gt(0xffffffffffffffff0000000000000000, 0xffffffffffffffff0000000000000000))
  sstore(9, gt(not(0), 0xffffffffffffffff0000000000000000ffffffffffffffff))
  sstore(10, gt(0xffffffffffffffff0000000000000000ffffffffffffffff, not(0)))
  sstore(11, gt(0xffffffffffffffff0000000000000000ffffffffffffffff, 0xffffffffffffffff0000000000000000ffffffffffffffff))
  sstore(12, gt(not(0), 0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000))
  sstore(13, gt(0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000, not(0)))
  sstore(14, gt(
    0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000,
    0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000)
  )
  sstore(15, gt(
      0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000001,
      0xffffffffffffffff0000000000000000ffffffffffffffff0000000000000000)
  )
}
// ----
// Trace:
// Memory dump:
//      0: 000000000000000000000000000000000000000000000000000000000000000f
//     20: 0000000000000000000000000000000000000000000000000000000000000001
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000003: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000006: 0000000000000000000000000000000000000000000000000000000000000001
//   0000000000000000000000000000000000000000000000000000000000000009: 0000000000000000000000000000000000000000000000000000000000000001
//   000000000000000000000000000000000000000000000000000000000000000c: 0000000000000000000000000000000000000000000000000000000000000001
//   000000000000000000000000000000000000000000000000000000000000000f: 0000000000000000000000000000000000000000000000000000000000000001
