{
  sstore(0, keccak256(0, 0))
  sstore(0, keccak256(0, 0x20))
}
// ----
// Trace:
// Memory dump:
//     20: 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
//   F000: 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
//   F020: 50b26c74e61920dce803cfd5efb93b017987cbe12a855a5651ec2a0ca0a92d66
//   F040: 329702dc584f4614c5d9b0d22c39051a125f3a8d44cc630f8fb63cc85f9b1a1e
//   F060: 94dbb49593e160114b712dd645a8b87475edb9301dd660112e6f279a8db8c17f
//   F080: 2c771e82e7f59c3dfe099aa9e9755682d0af8afd08bb994cc26bb92d042b28bf
//   F0A0: a439ea9c407f3d96b569b29a8cff6f52c9abc156cc3eb11e7b10daf2fcf11edd
//   F0C0: 5bf7f3a982b4c9f9000000000000000000000000000000000000000000000000
//   F0E0: 010000000000000082800000000000008a800000000000800080008000000080
//   F100: 8b80000000000000010000800000000081800080000000800980000000000080
//   F120: 8a00000000000000880000000000000009800080000000000a00008000000000
//   F140: 8b800080000000008b0000000000008089800000000000800380000000000080
//   F160: 028000000000008080000000000000800a800000000000000a00008000000080
//   F180: 8180008000000080808000000000008001000080000000000880008000000080
//   F1A0: 0103060a0f151c242d37020e1b293808192b3e12273d142c0a070b1112030510
//   F1C0: 081518040f17130d0c02140e16090601ec3daad9027f2dbaa379a03abc7f6593
//   F1E0: c90ce05fce3a303edf18d2a2fcba3adf58b7f38b3eb489f80000000000000000
//   F200: 000000000000000000000000000000005ddeb83b922abafb0000000000000000
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
