{
  mstore(0x20, 0x0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20)
  mstore(0x40, mload(0x20))
  sstore(1, mload(0x40))
}
// ----
// Trace:
// Memory dump:
//      0: 0000000000000000000000000000000000000000000000000000000000000001
//     20: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//     60: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
//     80: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000001: 0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20
