{
  sstore(0, signextend(0, 0x86))
  sstore(1, signextend(0, 0x76))
  sstore(2, signextend(32, not(0)))
  sstore(3, signextend(5, 0xff8844553322))
}
// ----
// Trace:
// Memory dump:
//      0: 0000000000000000000000000000000000000000000000000000000000000003
//     20: ffffffffffffffffffffffffffffffffffffffffffffffffffffff8844553322
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000000: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff86
//   0000000000000000000000000000000000000000000000000000000000000001: 0000000000000000000000000000000000000000000000000000000000000076
//   0000000000000000000000000000000000000000000000000000000000000002: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
//   0000000000000000000000000000000000000000000000000000000000000003: ffffffffffffffffffffffffffffffffffffffffffffffffffffff8844553322
