function(eth_apply TARGET REQUIRED)	
	find_package (Cpuid QUIET)
	eth_show_dependency(CPUID Cpuid)
	if (CPUID_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${CPUID_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${CPUID_LIBRARIES})
		target_compile_definitions(${TARGET} PUBLIC ETH_CPUID)
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "CPUID library not found")
	endif()
endfunction()
