function(eth_apply TARGET REQUIRED)	
	find_package (CryptoPP 5.6.2 REQUIRED)
	eth_show_dependency(CRYPTOPP CryptoPP)
	if (CRYPTOPP_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${CRYPTOPP_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${CRYPTOPP_LIBRARIES})
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "Cryptopp library not found")
	endif()
endfunction()
