function(eth_apply TARGET REQUIRED)	
	find_package (Jsoncpp 0.60)
	eth_show_dependency(JSONCPP JsonCpp)
	if (JSONCPP_FOUND)
		target_include_directories(${TARGET} SYSTEM BEFORE PUBLIC ${JSONCPP_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${JSONCPP_LIBRARIES})
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "Jsoncpp library not found")
	endif()
endfunction()
