function(eth_apply TARGET REQUIRED)	
	find_package(MHD ${REQUIRED})
	eth_show_dependency(MHD microhttpd)
	if (MHD_FOUND)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${MHD_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${MHD_LIBRARIES})
		eth_copy_dlls(${TARGET} MHD_DLLS)
	elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
		message(FATAL_ERROR "Microhttpd library not found")
	endif()
endfunction()
