{calldatacopy(444,44444,4)}
// ----
// Trace:
//   MSTORE_AT_SIZE(444, 4)
// Memory dump:
//      0: 0000000000000000000000000000000000000000000000000000000000000000
//     20: 0000000000000000000000000000000000000000000000000000000000000000
//     40: 0000000000000000000000000000000000000000000000000000000000000000
//     60: 0000000000000000000000000000000000000000000000000000000000000000
//     80: 0000000000000000000000000000000000000000000000000000000000000000
//     a0: 0000000000000000000000000000000000000000000000000000000000000000
//     c0: 0000000000000000000000000000000000000000000000000000000000000000
//     e0: 0000000000000000000000000000000000000000000000000000000000000000
//    100: 0000000000000000000000000000000000000000000000000000000000000000
//    120: 0000000000000000000000000000000000000000000000000000000000000000
//    140: 0000000000000000000000000000000000000000000000000000000000000000
//    160: 0000000000000000000000000000000000000000000000000000000000000000
//    180: 0000000000000000000000000000000000000000000000000000000000000000
//    1a0: 0000000000000000000000000000000000000000000000000000000000000000
// Storage dump:
