{
	let x := call(gas(), 0x45, 0x5, 0, 0x20, 0x30, 0x20)
	sstore(100, x)
}
// ----
// Trace:
//   GAS()
//   MLOAD_FROM_SIZE(0, 32)
//   MSTORE_AT_SIZE(48, 32)
//   CALL(153, 69, 5, 0, 32, 48, 32)
//   SSTORE(100, 1)
// Memory dump:
//      0: 0000000000000000000000000000000000000000000000000000000000000000
//     20: 0000000000000000000000000000000000000000000000000000000000000000
//     40: 0000000000000000000000000000000000000000000000000000000000000000
// Storage dump:
//   0000000000000000000000000000000000000000000000000000000000000064: 0000000000000000000000000000000000000000000000000000000000000001
