{
    mstore(0x00, 0x0000000000000000000000000000000000000000000000000000000000000000)
    mstore(0x20, 0x1111111122222222333333334444444455555555666666667777777788888888)
    mstore(0x40, 0x1111111122222222333333334444444455555555666666667777777788888888)
    mstore(0x60, 0x0000000000000000000000000000000000000000000000000000000000000000)

    mcopy(0x08, 0x20, 0x20)
    mcopy(0x58, 0x40, 0x20)
}
// ====
// EVMVersion: >=cancun
// ----
// Trace:
//   MCOPY(8, 32, 32)
//   MCOPY(88, 64, 32)
// Memory dump:
//      0: 0000000000000000111111112222222233333333444444445555555566666666
//     20: 7777777788888888333333334444444455555555666666667777777788888888
//     40: 1111111122222222333333334444444455555555666666661111111122222222
//     60: 3333333344444444555555556666666677777777888888880000000000000000
// Storage dump:
