(* Generated by coq-of-solidity *)
Require Import CoqOfSolidity.CoqOfSolidity.

(* Pragma abicoderv2 *)

(* Contract *)
Module C.
  (* Struct S2 *)

  (* Struct S *)

  Definition f (α : list Value.t) : M :=
    match α with
    | [s] =>
      let _ :=
        M.return_ (|
          Value.Tuple [
            M.member_access (|
              M.member_access (|
                M.get_name (| "s" |),
                "children"
              |),
              "length"
            |),
            M.member_access (|
              M.get_name (| "s" |),
              "a"
            |),
            M.member_access (|
              M.index_access (|
                M.member_access (|
                  M.get_name (| "s" |),
                  "children"
                |),
                Some (Value.Integer 0)
              |),
              "b"
            |),
            M.member_access (|
              M.index_access (|
                M.member_access (|
                  M.get_name (| "s" |),
                  "children"
                |),
                Some (Value.Integer 1)
              |),
              "b"
            |)
          ]
        |) in
      Value.Tuple []
    | _ => M.impossible "invalid number of parameters"
    end.
End C.
