{
    mstore(0x40, memoryguard(128))
    // ``f`` and ``g`` are mutually recursive and need no slots themselves, but ``f`` reaches ``h``,
    // which does. ``p`` calls into the cycle and needs a slot of its own, so it must not reuse the
    // slot of ``h``. Visiting ``f`` before ``p`` is what makes the requirements of the cycle
    // observable to ``p``.
    sstore(0, f())
    sstore(1, p())
    function f() -> v {
        v := add(h(), g())
    }
    function g() -> v {
        v := f()
    }
    function h() -> v {
        let a1 := calldataload(mul(1,4))
        let a2 := calldataload(mul(2,4))
        let a3 := calldataload(mul(3,4))
        let a4 := calldataload(mul(4,4))
        let a5 := calldataload(mul(5,4))
        let a6 := calldataload(mul(6,4))
        let a7 := calldataload(mul(7,4))
        let a8 := calldataload(mul(8,4))
        let a9 := calldataload(mul(9,4))
        a1 := calldataload(mul(0,4))
        let a10 := calldataload(mul(10,4))
        let a11 := calldataload(mul(11,4))
        let a12 := calldataload(mul(12,4))
        let a13 := calldataload(mul(13,4))
        let a14 := calldataload(mul(14,4))
        let a15 := calldataload(mul(15,4))
        let a16 := calldataload(mul(16,4))
        let a17 := calldataload(mul(17,4))
        sstore(0, a1)
        sstore(mul(17,4), a17)
        sstore(mul(16,4), a16)
        sstore(mul(15,4), a15)
        sstore(mul(14,4), a14)
        sstore(mul(13,4), a13)
        sstore(mul(12,4), a12)
        sstore(mul(11,4), a11)
        sstore(mul(10,4), a10)
        sstore(mul(9,4), a9)
        sstore(mul(8,4), a8)
        sstore(mul(7,4), a7)
        sstore(mul(6,4), a6)
        sstore(mul(5,4), a5)
        sstore(mul(4,4), a4)
        sstore(mul(3,4), a3)
        sstore(mul(2,4), a2)
        sstore(mul(1,4), a1)
    }
    function p() -> v {
        let b1 := calldataload(mul(1,5))
        let b2 := calldataload(mul(2,5))
        let b3 := calldataload(mul(3,5))
        let b4 := calldataload(mul(4,5))
        let b5 := calldataload(mul(5,5))
        let b6 := calldataload(mul(6,5))
        let b7 := calldataload(mul(7,5))
        let b8 := calldataload(mul(8,5))
        let b9 := calldataload(mul(9,5))
        b1 := calldataload(mul(0,5))
        let b10 := calldataload(mul(10,5))
        let b11 := calldataload(mul(11,5))
        let b12 := calldataload(mul(12,5))
        let b13 := calldataload(mul(13,5))
        let b14 := calldataload(mul(14,5))
        let b15 := calldataload(mul(15,5))
        let b16 := calldataload(mul(16,5))
        let b17 := calldataload(mul(17,5))
        v := g()
        sstore(0, b1)
        sstore(mul(17,5), b17)
        sstore(mul(16,5), b16)
        sstore(mul(15,5), b15)
        sstore(mul(14,5), b14)
        sstore(mul(13,5), b13)
        sstore(mul(12,5), b12)
        sstore(mul(11,5), b11)
        sstore(mul(10,5), b10)
        sstore(mul(9,5), b9)
        sstore(mul(8,5), b8)
        sstore(mul(7,5), b7)
        sstore(mul(6,5), b6)
        sstore(mul(5,5), b5)
        sstore(mul(4,5), b4)
        sstore(mul(3,5), b3)
        sstore(mul(2,5), b2)
        sstore(mul(1,5), b1)
    }
}
// ----
// step: stackLimitEvader
//
// {
//     mstore(0x40, memoryguard(0xc0))
//     sstore(0, f())
//     sstore(1, p())
//     function f() -> v
//     { v := add(h(), g()) }
//     function g() -> v_1
//     { v_1 := f() }
//     function h() -> v_2
//     {
//         mstore(0xa0, calldataload(mul(1, 4)))
//         let a2 := calldataload(mul(2, 4))
//         let a3 := calldataload(mul(3, 4))
//         let a4 := calldataload(mul(4, 4))
//         let a5 := calldataload(mul(5, 4))
//         let a6 := calldataload(mul(6, 4))
//         let a7 := calldataload(mul(7, 4))
//         let a8 := calldataload(mul(8, 4))
//         let a9 := calldataload(mul(9, 4))
//         mstore(0xa0, calldataload(mul(0, 4)))
//         let a10 := calldataload(mul(10, 4))
//         let a11 := calldataload(mul(11, 4))
//         let a12 := calldataload(mul(12, 4))
//         let a13 := calldataload(mul(13, 4))
//         let a14 := calldataload(mul(14, 4))
//         let a15 := calldataload(mul(15, 4))
//         let a16 := calldataload(mul(16, 4))
//         let a17 := calldataload(mul(17, 4))
//         sstore(0, mload(0xa0))
//         sstore(mul(17, 4), a17)
//         sstore(mul(16, 4), a16)
//         sstore(mul(15, 4), a15)
//         sstore(mul(14, 4), a14)
//         sstore(mul(13, 4), a13)
//         sstore(mul(12, 4), a12)
//         sstore(mul(11, 4), a11)
//         sstore(mul(10, 4), a10)
//         sstore(mul(9, 4), a9)
//         sstore(mul(8, 4), a8)
//         sstore(mul(7, 4), a7)
//         sstore(mul(6, 4), a6)
//         sstore(mul(5, 4), a5)
//         sstore(mul(4, 4), a4)
//         sstore(mul(3, 4), a3)
//         sstore(mul(2, 4), a2)
//         sstore(mul(1, 4), mload(0xa0))
//     }
//     function p() -> v_3
//     {
//         mstore(0xa0, 0)
//         p_1()
//         v_3 := mload(0xa0)
//     }
//     function p_1()
//     {
//         mstore(0x80, calldataload(mul(1, 5)))
//         let b2 := calldataload(mul(2, 5))
//         let b3 := calldataload(mul(3, 5))
//         let b4 := calldataload(mul(4, 5))
//         let b5 := calldataload(mul(5, 5))
//         let b6 := calldataload(mul(6, 5))
//         let b7 := calldataload(mul(7, 5))
//         let b8 := calldataload(mul(8, 5))
//         let b9 := calldataload(mul(9, 5))
//         mstore(0x80, calldataload(mul(0, 5)))
//         let b10 := calldataload(mul(10, 5))
//         let b11 := calldataload(mul(11, 5))
//         let b12 := calldataload(mul(12, 5))
//         let b13 := calldataload(mul(13, 5))
//         let b14 := calldataload(mul(14, 5))
//         let b15 := calldataload(mul(15, 5))
//         let b16 := calldataload(mul(16, 5))
//         let b17 := calldataload(mul(17, 5))
//         mstore(0xa0, g())
//         sstore(0, mload(0x80))
//         sstore(mul(17, 5), b17)
//         sstore(mul(16, 5), b16)
//         sstore(mul(15, 5), b15)
//         sstore(mul(14, 5), b14)
//         sstore(mul(13, 5), b13)
//         sstore(mul(12, 5), b12)
//         sstore(mul(11, 5), b11)
//         sstore(mul(10, 5), b10)
//         sstore(mul(9, 5), b9)
//         sstore(mul(8, 5), b8)
//         sstore(mul(7, 5), b7)
//         sstore(mul(6, 5), b6)
//         sstore(mul(5, 5), b5)
//         sstore(mul(4, 5), b4)
//         sstore(mul(3, 5), b3)
//         sstore(mul(2, 5), b2)
//         sstore(mul(1, 5), mload(0x80))
//     }
// }
