{
    {
        mstore(0x40, memoryguard(128))
        sstore(23, f())
    }
    function f() -> v{
        let a1 := calldataload(mul(1,4))
        let a2 := calldataload(mul(2,4))
        let a3 := calldataload(mul(3,4))
        let a4 := calldataload(g())
        let a5 := calldataload(mul(5,4))
        let a6 := calldataload(mul(6,4))
        let a7 := calldataload(mul(7,4))
        let a8 := calldataload(mul(8,4))
        let a9 := calldataload(mul(9,4))
        a1 := calldataload(mul(0,4))
        let a10 := calldataload(mul(10,4))
        let a11 := calldataload(mul(11,4))
        let a12 := calldataload(mul(12,4))
        let a13 := calldataload(mul(13,4))
        let a14 := calldataload(mul(14,4))
        let a15 := calldataload(mul(15,4))
        let a16 := calldataload(mul(16,4))
        let a17 := calldataload(mul(17,4))
        sstore(0, a1)
        sstore(mul(17,4), a17)
        sstore(mul(16,4), a16)
        sstore(mul(15,4), a15)
        sstore(mul(14,4), a14)
        sstore(mul(13,4), a13)
        sstore(mul(12,4), a12)
        sstore(mul(11,4), a11)
        sstore(mul(10,4), a10)
        sstore(mul(9,4), a9)
        sstore(mul(8,h()), a8)
        sstore(mul(7,4), a7)
        sstore(mul(6,4), a6)
        sstore(mul(5,4), a5)
        sstore(mul(4,4), a4)
        sstore(mul(3,4), a3)
        sstore(mul(2,4), a2)
        sstore(mul(1,4), a1)
    }
    function g() -> v {
        let a1 := calldataload(mul(1,4))
        let a2 := calldataload(mul(2,4))
        let a3 := calldataload(mul(3,4))
        let a4 := calldataload(mul(4,4))
        let a5 := calldataload(mul(5,4))
        let a6 := calldataload(mul(6,4))
        let a7 := calldataload(mul(7,4))
        let a8 := calldataload(mul(8,4))
        let a9 := calldataload(mul(9,4))
        a1 := calldataload(mul(0,4))
        let a10 := calldataload(mul(10,4))
        let a11 := calldataload(mul(11,4))
        let a12 := calldataload(mul(12,4))
        let a13 := calldataload(mul(13,4))
        let a14 := calldataload(mul(14,4))
        let a15 := calldataload(mul(15,4))
        let a16 := calldataload(mul(16,4))
        let a17 := calldataload(mul(17,4))
        sstore(0, a1)
        sstore(mul(17,4), a17)
        sstore(mul(16,4), a16)
        sstore(mul(15,4), a15)
        sstore(mul(14,4), a14)
        sstore(mul(13,4), a13)
        sstore(mul(12,4), a12)
        sstore(mul(11,4), a11)
        sstore(mul(10,4), a10)
        sstore(mul(9,4), a9)
        sstore(mul(8,4), a8)
        sstore(mul(7,4), a7)
        sstore(mul(6,4), a6)
        sstore(mul(5,4), a5)
        sstore(mul(4,4), a4)
        sstore(mul(3,4), a3)
        sstore(mul(2,4), a2)
        sstore(mul(1,4), a1)
        v := i()
    }
    function h() -> v {
        let a1 := calldataload(mul(1,4))
        let a2 := calldataload(mul(2,4))
        let a3 := calldataload(mul(3,4))
        let a4 := calldataload(mul(4,4))
        let a5 := calldataload(mul(5,4))
        let a6 := calldataload(mul(6,4))
        let a7 := calldataload(mul(7,4))
        let a8 := calldataload(mul(8,4))
        let a9 := calldataload(mul(9,4))
        let a10 := calldataload(mul(10,4))
        let a11 := calldataload(mul(10,4))
        a1 := calldataload(mul(0,4))
        a2 := calldataload(mul(1,4))
        let a12 := calldataload(mul(12,4))
        let a13 := calldataload(mul(13,4))
        let a14 := calldataload(mul(14,4))
        let a15 := calldataload(mul(15,4))
        let a16 := calldataload(mul(16,4))
        let a17 := calldataload(mul(17,4))
        let a18 := calldataload(mul(18,4))
        let a19 := calldataload(mul(19,4))
        sstore(0, add(a1, a2))
        sstore(mul(17,4), a19)
        sstore(mul(17,4), a18)
        sstore(mul(17,4), a17)
        sstore(mul(16,4), a16)
        sstore(mul(15,4), a15)
        sstore(mul(14,4), a14)
        sstore(mul(13,4), a13)
        sstore(mul(12,4), a12)
        sstore(mul(11,4), a11)
        sstore(mul(10,4), a10)
        sstore(mul(9,4), a9)
        sstore(mul(8,4), a8)
        sstore(mul(7,4), a7)
        sstore(mul(6,4), a6)
        sstore(mul(5,4), a5)
        sstore(mul(4,4), a4)
        sstore(mul(3,4), a3)
        sstore(mul(2,4), a2)
        sstore(mul(1,4), a1)
        v := i()
    }
    function i() -> v {
        let a1 := calldataload(mul(1,4))
        let a2 := calldataload(mul(2,4))
        let a3 := calldataload(mul(3,4))
        let a4 := calldataload(mul(4,4))
        let a5 := calldataload(mul(5,4))
        let a6 := calldataload(mul(6,4))
        let a7 := calldataload(mul(7,4))
        let a8 := calldataload(mul(8,4))
        let a9 := calldataload(mul(9,4))
        a1 := calldataload(mul(0,4))
        let a10 := calldataload(mul(10,4))
        let a11 := calldataload(mul(11,4))
        let a12 := calldataload(mul(12,4))
        let a13 := calldataload(mul(13,4))
        let a14 := calldataload(mul(14,4))
        let a15 := calldataload(mul(15,4))
        let a16 := calldataload(mul(16,4))
        let a17 := calldataload(mul(17,4))
        sstore(0, a1)
        sstore(mul(17,4), a17)
        sstore(mul(16,4), a16)
        sstore(mul(15,4), a15)
        sstore(mul(14,4), a14)
        sstore(mul(13,4), a13)
        sstore(mul(12,4), a12)
        sstore(mul(11,4), a11)
        sstore(mul(10,4), a10)
        sstore(mul(9,4), a9)
        sstore(mul(8,4), a8)
        sstore(mul(7,4), a7)
        sstore(mul(6,4), a6)
        sstore(mul(5,4), a5)
        sstore(mul(4,4), a4)
        sstore(mul(3,4), a3)
        sstore(mul(2,4), a2)
        sstore(mul(1,4), a1)
        v := sload(mul(42,8))
    }
}
// ----
// step: stackLimitEvader
//
// {
//     {
//         mstore(0x40, memoryguard(0x0100))
//         sstore(23, f())
//     }
//     function f() -> v
//     {
//         mstore(0x80, calldataload(mul(1, 4)))
//         let a2 := calldataload(mul(2, 4))
//         let a3 := calldataload(mul(3, 4))
//         let a4 := calldataload(g())
//         let a5 := calldataload(mul(5, 4))
//         let a6 := calldataload(mul(6, 4))
//         let a7 := calldataload(mul(7, 4))
//         let a8 := calldataload(mul(8, 4))
//         let a9 := calldataload(mul(9, 4))
//         mstore(0x80, calldataload(mul(0, 4)))
//         let a10 := calldataload(mul(10, 4))
//         let a11 := calldataload(mul(11, 4))
//         let a12 := calldataload(mul(12, 4))
//         let a13 := calldataload(mul(13, 4))
//         let a14 := calldataload(mul(14, 4))
//         let a15 := calldataload(mul(15, 4))
//         let a16 := calldataload(mul(16, 4))
//         let a17 := calldataload(mul(17, 4))
//         sstore(0, mload(0x80))
//         sstore(mul(17, 4), a17)
//         sstore(mul(16, 4), a16)
//         sstore(mul(15, 4), a15)
//         sstore(mul(14, 4), a14)
//         sstore(mul(13, 4), a13)
//         sstore(mul(12, 4), a12)
//         sstore(mul(11, 4), a11)
//         sstore(mul(10, 4), a10)
//         sstore(mul(9, 4), a9)
//         sstore(mul(8, h()), a8)
//         sstore(mul(7, 4), a7)
//         sstore(mul(6, 4), a6)
//         sstore(mul(5, 4), a5)
//         sstore(mul(4, 4), a4)
//         sstore(mul(3, 4), a3)
//         sstore(mul(2, 4), a2)
//         sstore(mul(1, 4), mload(0x80))
//     }
//     function g() -> v_1
//     {
//         mstore(0xc0, calldataload(mul(1, 4)))
//         let a2_1 := calldataload(mul(2, 4))
//         let a3_1 := calldataload(mul(3, 4))
//         let a4_1 := calldataload(mul(4, 4))
//         let a5_1 := calldataload(mul(5, 4))
//         let a6_1 := calldataload(mul(6, 4))
//         let a7_1 := calldataload(mul(7, 4))
//         let a8_1 := calldataload(mul(8, 4))
//         let a9_1 := calldataload(mul(9, 4))
//         mstore(0xc0, calldataload(mul(0, 4)))
//         let a10_1 := calldataload(mul(10, 4))
//         let a11_1 := calldataload(mul(11, 4))
//         let a12_1 := calldataload(mul(12, 4))
//         let a13_1 := calldataload(mul(13, 4))
//         let a14_1 := calldataload(mul(14, 4))
//         let a15_1 := calldataload(mul(15, 4))
//         let a16_1 := calldataload(mul(16, 4))
//         let a17_1 := calldataload(mul(17, 4))
//         sstore(0, mload(0xc0))
//         sstore(mul(17, 4), a17_1)
//         sstore(mul(16, 4), a16_1)
//         sstore(mul(15, 4), a15_1)
//         sstore(mul(14, 4), a14_1)
//         sstore(mul(13, 4), a13_1)
//         sstore(mul(12, 4), a12_1)
//         sstore(mul(11, 4), a11_1)
//         sstore(mul(10, 4), a10_1)
//         sstore(mul(9, 4), a9_1)
//         sstore(mul(8, 4), a8_1)
//         sstore(mul(7, 4), a7_1)
//         sstore(mul(6, 4), a6_1)
//         sstore(mul(5, 4), a5_1)
//         sstore(mul(4, 4), a4_1)
//         sstore(mul(3, 4), a3_1)
//         sstore(mul(2, 4), a2_1)
//         sstore(mul(1, 4), mload(0xc0))
//         v_1 := i()
//     }
//     function h() -> v_2
//     {
//         mstore(0xa0, calldataload(mul(1, 4)))
//         mstore(0xc0, calldataload(mul(2, 4)))
//         let a3_2 := calldataload(mul(3, 4))
//         let a4_2 := calldataload(mul(4, 4))
//         let a5_2 := calldataload(mul(5, 4))
//         let a6_2 := calldataload(mul(6, 4))
//         let a7_2 := calldataload(mul(7, 4))
//         let a8_2 := calldataload(mul(8, 4))
//         let a9_2 := calldataload(mul(9, 4))
//         let a10_2 := calldataload(mul(10, 4))
//         let a11_2 := calldataload(mul(10, 4))
//         mstore(0xa0, calldataload(mul(0, 4)))
//         mstore(0xc0, calldataload(mul(1, 4)))
//         let a12_2 := calldataload(mul(12, 4))
//         let a13_2 := calldataload(mul(13, 4))
//         let a14_2 := calldataload(mul(14, 4))
//         let a15_2 := calldataload(mul(15, 4))
//         let a16_2 := calldataload(mul(16, 4))
//         let a17_2 := calldataload(mul(17, 4))
//         let a18 := calldataload(mul(18, 4))
//         let a19 := calldataload(mul(19, 4))
//         sstore(0, add(mload(0xa0), mload(0xc0)))
//         sstore(mul(17, 4), a19)
//         sstore(mul(17, 4), a18)
//         sstore(mul(17, 4), a17_2)
//         sstore(mul(16, 4), a16_2)
//         sstore(mul(15, 4), a15_2)
//         sstore(mul(14, 4), a14_2)
//         sstore(mul(13, 4), a13_2)
//         sstore(mul(12, 4), a12_2)
//         sstore(mul(11, 4), a11_2)
//         sstore(mul(10, 4), a10_2)
//         sstore(mul(9, 4), a9_2)
//         sstore(mul(8, 4), a8_2)
//         sstore(mul(7, 4), a7_2)
//         sstore(mul(6, 4), a6_2)
//         sstore(mul(5, 4), a5_2)
//         sstore(mul(4, 4), a4_2)
//         sstore(mul(3, 4), a3_2)
//         sstore(mul(2, 4), mload(0xc0))
//         sstore(mul(1, 4), mload(0xa0))
//         v_2 := i()
//     }
//     function i() -> v_3
//     {
//         mstore(0xe0, calldataload(mul(1, 4)))
//         let a2_3 := calldataload(mul(2, 4))
//         let a3_3 := calldataload(mul(3, 4))
//         let a4_3 := calldataload(mul(4, 4))
//         let a5_3 := calldataload(mul(5, 4))
//         let a6_3 := calldataload(mul(6, 4))
//         let a7_3 := calldataload(mul(7, 4))
//         let a8_3 := calldataload(mul(8, 4))
//         let a9_3 := calldataload(mul(9, 4))
//         mstore(0xe0, calldataload(mul(0, 4)))
//         let a10_3 := calldataload(mul(10, 4))
//         let a11_3 := calldataload(mul(11, 4))
//         let a12_3 := calldataload(mul(12, 4))
//         let a13_3 := calldataload(mul(13, 4))
//         let a14_3 := calldataload(mul(14, 4))
//         let a15_3 := calldataload(mul(15, 4))
//         let a16_3 := calldataload(mul(16, 4))
//         let a17_3 := calldataload(mul(17, 4))
//         sstore(0, mload(0xe0))
//         sstore(mul(17, 4), a17_3)
//         sstore(mul(16, 4), a16_3)
//         sstore(mul(15, 4), a15_3)
//         sstore(mul(14, 4), a14_3)
//         sstore(mul(13, 4), a13_3)
//         sstore(mul(12, 4), a12_3)
//         sstore(mul(11, 4), a11_3)
//         sstore(mul(10, 4), a10_3)
//         sstore(mul(9, 4), a9_3)
//         sstore(mul(8, 4), a8_3)
//         sstore(mul(7, 4), a7_3)
//         sstore(mul(6, 4), a6_3)
//         sstore(mul(5, 4), a5_3)
//         sstore(mul(4, 4), a4_3)
//         sstore(mul(3, 4), a3_3)
//         sstore(mul(2, 4), a2_3)
//         sstore(mul(1, 4), mload(0xe0))
//         v_3 := sload(mul(42, 8))
//     }
// }
